// Design reminder: This static prototype renders one connected AI Sales Engine workflow. It intentionally uses local mock data and route state only — no backend, scraping, APIs, or authentication service.
import { state, navItems } from "./data.js";
import { getRoute, go } from "./router.js";
import { renderDashboard } from "./dashboard.js";
import { renderUiKit } from "./ui-kit.js";

const app = document.getElementById("app");
const icon = (text) => `<span class="nav-icon">${text}</span>`;
const fmt = (number) => new Intl.NumberFormat("ar-SA").format(number);
const sar = (number) => `SAR ${fmt(number)}`;
const shipments = { discovery:"S3", "discovery-jobs":"S3", results:"S3", intelligence:"S4", "lead-profile":"S4", leads:"S4", contacts:"S5", companies:"S5", pipeline:"S5", deals:"S5", tasks:"S5", appointments:"S5", inbox:"S6", whatsapp:"S6", calls:"S6", copilot:"S7", agent:"S7", automation:"S7", analytics:"S8", integrations:"S9", settings:"S9" };

function brand() { return `<a class="brand" href="#/"><img src="/manus-storage/leadflow-orbit-mark_f6c27956.png" alt="نمو"/><span><b>نمو</b><small>منصة مبيعات ذكية</small></span></a>`; }
function button(label, action, cls = "button") { return `<button class="${cls}" type="button" data-action="${action}">${label}</button>`; }
function pageHead(kicker, title, description, actions = "") { return `<header class="page-head"><div><p class="eyebrow">${kicker}</p><h1>${title}</h1>${description ? `<p>${description}</p>` : ""}</div><div class="page-head-actions">${actions}</div></header>`; }
function toast(message, type = "") { const wrap = document.querySelector(".toast-wrap") || Object.assign(document.body.appendChild(document.createElement("div")), { className: "toast-wrap" }); const el = document.createElement("div"); el.className = `toast ${type}`; el.innerHTML = `<i></i><span>${message}</span>`; wrap.appendChild(el); setTimeout(() => el.remove(), 3300); }
function statusClass(stage) { if (["Qualified", "Won", "completed"].includes(stage)) return "qualified"; if (["Contacted", "Meeting", "Proposal", "processing"].includes(stage)) return "contact"; if (stage === "New") return "new"; return "pending"; }

function renderLanding() {
  const workflow = [["01","اكتشف","حدد القطاع والموقع والمعايير."],["02","افهم","حلّل الحضور الرقمي والإشارات وفرص البيع."],["03","رتّب","احصل على درجة فرصة وأولوية واضحة."],["04","تواصل","انقل العميل إلى إدارة العملاء وابدأ المتابعة."],["05","حوّل","تابع الصفقة واعرف أي مصدر أنتج الإيراد."]];
  const integrations = [["خرائط الأعمال","متاح للربط"],["واتساب","مخطط"],["إنستغرام","قريبًا"],["دردشة الموقع","مخطط"],["التقويم","قريبًا"],["نظام إدارة العملاء","متاح للاستيراد"],["الخطافات البرمجية","مخطط"],["واجهة برمجية","مخطط"]];
  return `<div class="public-shell landing-shell">
    <nav class="public-nav landing-nav" aria-label="التنقل العام">${brand()}<div class="public-nav-links"><a href="#platform">المنصة</a><a href="#workflow">كيف تعمل</a><a href="#intelligence">الذكاء الاصطناعي</a><a href="#uses">الاستخدامات</a><a href="#/login">الدخول</a></div><div class="public-actions">${button("ابدأ الآن", "go-onboarding", "button primary")}</div></nav>
    <main>
      <section class="hero landing-hero" id="platform"><div class="hero-copy"><p class="eyebrow">منصة ذكاء المبيعات واكتساب العملاء</p><h1>من اكتشاف العميل إلى إغلاق الصفقة — في منصة واحدة</h1><p class="lead">اكتشف الشركات المناسبة، حلّل فرص البيع لديها، رتّب أولويات فريقك، تواصل مع العملاء، وتابع رحلة البيع كاملة حتى الإيراد.</p><div class="hero-actions">${button("ابدأ تجربة المنصة", "go-onboarding", "button primary")}${button("شاهد كيف تعمل", "scroll-workflow", "button")}</div><p class="hero-note"><i></i>نموذج تفاعلي ببيانات تجريبية؛ لا توجد عمليات بحث أو رسائل أو تكاملات حقيقية.</p></div><div class="hero-visual source-revenue-visual"><div class="source-revenue-head"><span>رحلة مصدر إلى إيراد</span><b>سجل قابل للتتبع</b></div><div class="source-query"><span>بحث</span><b>عيادات أسنان — الرياض</b><small class="mono">JOB-1028</small></div><div class="source-flow">${[["١٬٢٤٠","شركة مكتشفة","اكتشاف"],["٣٨٠","فرصة مناسبة","تحليل"],["٨٤","عميل مؤهل","تأهيل"],["٣٢","صفقة نشطة","مبيعات"],["١١","صفقة رابحة","إيراد"]].map(([n,label,stage],index)=>`<div class="source-flow-row ${index===4?"revenue-row":""}"><i>${index+1}</i><div><span>${stage}</span><b>${label}</b></div><strong>${n}</strong></div>`).join("")}</div><div class="source-revenue-footer"><span>الإيراد المنسوب</span><b>٤٢٨٬٠٠٠ ر.س</b><small>بيانات تجريبية لغرض عرض تجربة المنتج</small></div></div></section>
      <section class="workflow-strip" id="workflow"><div class="landing-section-title"><p class="eyebrow">سير العمل</p><h2>كيف تعمل المنصة؟</h2><p>لا تبدأ من قائمة أسماء؛ بل من إشارة يمكن تتبعها حتى نتيجة بيع واضحة.</p></div><div class="workflow-steps product-workflow">${workflow.map(([n,a,b])=>`<article class="workflow-step"><span>${n}</span><b>${a}</b><small>${b}</small></article>`).join("")}</div></section>
      <section class="landing-section discovery-section"><div class="section-head"><div><p class="eyebrow">اكتشاف مدعوم بالبيانات</p><h2>لا تبحث عن أسماء فقط — ابحث عن فرص بيع</h2></div><p>كل شركة تظهر كسجل قابل للفهم، وليس كسطر معزول في ملف.</p></div><div class="discovery-showcase"><article class="business-preview"><header><div><span class="eyebrow">سجل شركة</span><h3>عيادات ابتسامة الرياض</h3><small class="mono">BUS-1042 · الرياض</small></div><span class="score high">92</span></header><div class="business-facts"><span><small>التقييم</small><b>٤٫٧</b></span><span><small>المراجعات</small><b>٨٦٣</b></span><span><small>الموقع</small><b class="text-red">ضعيف</b></span><span><small>واتساب</small><b class="text-green">متاح</b></span><span><small>الحضور الاجتماعي</small><b class="text-green">نشط</b></span><span><small>درجة الفرصة</small><b>٩٢ / ١٠٠</b></span></div><footer><span>الفرص المكتشفة</span><div><em>تطوير الموقع</em><em>تحسين الظهور</em><em>أتمتة المتابعة</em></div></footer></article><aside class="discovery-copy"><p class="eyebrow">من مصدر أعمال إلى سياق بيع</p><h3>تبدأ الرحلة بالمصدر، لكنها لا تنتهي عنده.</h3><p>يُحفظ الأصل، ثم تُضاف إشارات النشاط والفجوات الرقمية والتوصية الخدمية بجانب الشركة لتوجيه الفريق إلى الخطوة التالية.</p>${button("اكتشف كيف يتم تحليل الفرص", "show-landing-demo", "button")}</aside></div></section>
      <section class="landing-section intelligence-section" id="intelligence"><div class="section-head"><div><p class="eyebrow">ذكاء فرص العملاء</p><h2>كل عميل يأتي مع سبب واضح لكونه فرصة</h2></div><p>الذكاء الاصطناعي هنا طبقة تحليل وقرار، وليس نافذة محادثة منفصلة.</p></div><div class="intelligence-showcase"><article class="intelligence-reason"><header><span>لماذا هذا العميل مهم؟</span><b>إشارة مركبة</b></header><p>لديه نشاط قوي وتقييم مرتفع، لكن مسار التواصل والتحويل الرقمي ضعيف.</p><div class="signal-list"><span><i>✓</i>حضور رقمي نشط</span><span><i>✓</i>مراجعات مرتفعة</span><span><i>!</i>موقع يحتاج تحديثًا</span><span><i>!</i>مسار واتساب غير مؤتمت</span></div><footer><small>الخدمة المقترحة</small><b>تحديث الموقع + تحسين الظهور + أتمتة واتساب</b></footer></article><article class="intelligence-meta"><span>درجة الفرصة</span><b class="mono">92/100</b><small>ثقة مرتفعة · مراجعة بشرية مطلوبة</small><div><em>الفجوات المكتشفة</em><em>أسلوب البيع المقترح</em><em>الإجراء التالي</em></div></article></div></section>
      <section class="landing-section context-section"><div class="section-head"><div><p class="eyebrow">سياق متصل</p><h2>لا تفقد سياق العميل بعد الاكتشاف</h2></div><p>تتحرك نفس الهوية من الشركة إلى العميل المحتمل والمحادثة والصفقة ثم الإيراد.</p></div><div class="record-chain"><article><span class="mono">BUS-1042</span><b>شركة</b><small>البيانات والإشارات</small></article><i>↓</i><article><span class="mono">LEAD-1042</span><b>عميل محتمل</b><small>المالك ودرجة الفرصة</small></article><i>↓</i><article><span class="mono">CONV-3042</span><b>محادثة</b><small>السياق والمتابعة</small></article><i>↓</i><article><span class="mono">DEAL-4042</span><b>صفقة</b><small>القيمة والمرحلة</small></article><i>↓</i><article class="revenue"><span>٤٢٨٬٠٠٠ ر.س</span><b>إيراد</b><small>منسوب إلى المصدر</small></article></div></section>
      <section class="landing-section copilot-section"><div class="copilot-landing"><div><p class="eyebrow">مساعد المبيعات الذكي</p><h2>الذكاء الاصطناعي يساعد فريق المبيعات على اتخاذ الخطوة التالية</h2><p>يربط الإشارة والوقت والسياق ليقترح الإجراء التالي، بينما تبقى المراجعة البشرية جزءًا أساسيًا من القرار.</p></div><article><span>تنبيه متابعة</span><h3>العميل لم يرد منذ ٣ أيام.</h3><dl><div><dt>الفرصة</dt><dd>مرتفعة</dd></div><div><dt>أفضل إجراء الآن</dt><dd>متابعة عبر واتساب</dd></div><div><dt>احتمال الإغلاق</dt><dd>٧٢٪</dd></div></dl><div class="copilot-actions">${["صياغة متابعة","إنشاء مهمة","تلخيص العميل","اقتراح الخطوة التالية"].map(label=>button(label,"show-landing-demo","button")).join("")}</div></article></div></section>
      <section class="landing-section pipeline-section"><div class="section-head"><div><p class="eyebrow">متابعة المبيعات</p><h2>مسار بسيط يوضح أين تقف كل فرصة</h2></div><p>معاينة محدودة للرحلة، دون تحويل Landing إلى لوحة تشغيل مزدحمة.</p></div><div class="landing-kanban">${[["جديد",["عيادات الحياة","مؤسسة ابتكار"]],["تم التواصل",["مركز ابتسامة"]],["مؤهل",["مجمع رؤية"]],["اجتماع",["شركة المدار"]],["عرض",["شركة المدار"]],["تفاوض",[]],["رابح",["عيادات الشروق"]]].map(([stage,leads])=>`<article><header><b>${stage}</b><small>${leads.length}</small></header>${leads.length?leads.map(lead=>`<div><span>${lead.slice(0,1)}</span><b>${lead}</b><small>متابعة قريبة</small></div>`).join(""):`<p>لا توجد فرصة</p>`}</article>`).join("")}</div></section>
      <section class="landing-section attribution-section"><div class="attribution-landing"><header><p class="eyebrow">نسبة الإيراد</p><h2>اعرف أي عملية اكتشاف أنتجت الإيراد</h2><p>لا تُقاس النتيجة بالانطباع؛ بل تربط رحلة البيع بعملية البحث الأصلية.</p></header><div class="attribution-landing-flow"><article><span>عملية البحث</span><b>عيادات أسنان — الرياض</b><small class="mono">JOB-1028</small></article><i>↓</i><article><span>مكتشف</span><b>١٬٢٤٠</b></article><i>↓</i><article><span>مؤهل</span><b>٨٤</b></article><i>↓</i><article><span>صفقات</span><b>٣٢</b></article><i>↓</i><article class="won"><span>رابحة</span><b>١١</b></article><i>↓</i><article class="revenue"><span>الإيراد</span><b>٤٢٨٬٠٠٠ ر.س</b></article></div></div></section>
      <section class="landing-section uses-section" id="uses"><div class="section-head"><div><p class="eyebrow">لمن صُممت</p><h2>للفرق التي تريد تحويل الإشارات إلى قرارات بيع</h2></div><p>تركيز واضح على حالات الاستخدام التي تحتاج اكتسابًا منظمًا ومتابعة قابلة للقياس.</p></div><div class="uses-grid">${["وكالات التسويق","فرق مبيعات الشركات","شركات الخدمات","العقار","العيادات","شركات التقنية","فرق توليد العملاء"].map((use,index)=>`<article><i>${String(index+1).padStart(2,"0")}</i><b>${use}</b><span>اكتشاف، فهم، متابعة، وقياس.</span></article>`).join("")}</div></section>
      <section class="landing-section integrations-preview"><div class="section-head"><div><p class="eyebrow">طبقة تكامل</p><h2>مصادر وقنوات ووجهات ضمن مسار واحد</h2></div><p>المعروض أدناه حالة تخطيطية داخل Prototype ولا يمثل تكاملات تشغيلية حقيقية.</p></div><div class="integration-preview-grid">${integrations.map(([name,status],index)=>`<article><i>${String(index+1).padStart(2,"0")}</i><div><b>${name}</b><small class="${status==="متاح للربط"?"available":status==="قريبًا"?"soon":"planned"}">${status}</small></div></article>`).join("")}</div></section>
      <section class="final-cta"><div><p class="eyebrow">ابدأ من مسار واضح</p><h2>حوّل اكتشاف العملاء إلى عملية مبيعات قابلة للقياس</h2><p>ابدأ بإعداد مساحة العمل، ثم اتبع رحلة تجريبية تشرح كيف تتصل البيانات والفرص والمبيعات.</p></div><div>${button("ابدأ الآن","go-onboarding","button primary")}${button("استكشف المنصة","go-login","button")}</div></section>
    </main>
    <footer class="landing-footer"><div>${brand()}<p>نموذج تجريبي لعرض تجربة منتج اكتساب العملاء والمبيعات.</p></div><div><b>المنتج</b><a href="#platform">المنصة</a><a href="#workflow">الاكتشاف</a><a href="#workflow">إدارة العملاء</a><a href="#intelligence">الذكاء الاصطناعي</a><a href="#workflow">التحليلات</a></div><div><b>الشركة</b><a href="#platform">عن المنصة</a><a href="#/login">التواصل</a><a href="#/login">الخصوصية</a><a href="#/login">الشروط</a></div><div><b>تقني</b><a href="#/login">واجهة برمجية</a><a href="#/login">تكاملات</a><a href="#/login">التوثيق</a></div></footer>
  </div>`;
}
function renderLogin() {
  const errors = state.loginErrors;
  return `<div class="auth-shell"><section class="auth-panel"><form class="auth-form" data-form="login" novalidate>${brand()}<p class="eyebrow">دخول تجريبي</p><h1>مرحبًا بعودتك</h1><p>ادخل إلى مساحة العمل لمتابعة العملاء والصفقات. لا توجد مصادقة أو حسابات حقيقية في هذا النموذج.</p><div class="form-grid"><div class="form-field wide ${errors.email?"has-error":""}"><label for="loginEmail">البريد الإلكتروني</label><input id="loginEmail" name="email" class="ltr" type="email" aria-invalid="${Boolean(errors.email)}" aria-describedby="loginEmailError" placeholder="name@company.sa"/><small id="loginEmailError" class="field-error">${errors.email || ""}</small></div><div class="form-field wide ${errors.password?"has-error":""}"><label for="loginPassword">كلمة المرور</label><input id="loginPassword" name="password" class="ltr" type="password" aria-invalid="${Boolean(errors.password)}" aria-describedby="loginPasswordError" placeholder="••••••••"/><small id="loginPasswordError" class="field-error">${errors.password || ""}</small></div></div><div class="auth-row"><label class="check"><input name="remember" type="checkbox"/> تذكرني في هذه الجلسة</label><button class="button ghost" data-action="forgot-password" type="button">نسيت كلمة المرور؟</button></div><button class="button primary auth-submit" type="submit">تسجيل الدخول</button><p class="auth-helper">ليس لديك إعداد تجريبي؟ <button class="button ghost inline-button" data-action="go-onboarding" type="button">ابدأ الإعداد الآن</button></p></form></section><aside class="auth-visual"><div class="auth-story"><p class="eyebrow">منصة مبيعات ذكية</p><h2>اكتشاف أذكى. متابعة أوضح. إيراد قابل للقياس.</h2><p>لا تبدأ من جدول معزول؛ ابدأ من فهم الشركة، ثم أبنِ سياق البيع حولها.</p><ul><li><i></i>اكتشاف وإثراء العملاء المحتملين</li><li><i></i>مساعد مبيعات ذكي داخل المحادثة</li><li><i></i>نسبة الإيراد إلى مصدر الاكتشاف</li></ul></div></aside></div>`;
}
function onboardingChoice(collection, value, label) { const selected = state.workspace[collection].includes(value); return `<button type="button" class="onboarding-choice ${selected?"selected":""}" data-onboarding-choice="${collection}" data-value="${value}" aria-pressed="${selected}"><i>${selected?"✓":""}</i><span>${label}</span></button>`; }
function onboardingError(key) { return state.onboardingErrors[key] ? `<p class="wizard-error" role="alert">${state.onboardingErrors[key]}</p>` : ""; }
function renderOnboardingStep() {
  const w = state.workspace; const step = state.onboardingStep;
  if (step === 1) return `<form class="wizard-form" data-form="onboarding" data-step="1" novalidate><h1>أخبرنا عن شركتك</h1><p>نستخدم هذه المعلومات لتهيئة مساحة العمل التجريبية فقط.</p><div class="form-grid"><div class="form-field wide"><label for="workspaceName">اسم الشركة</label><input id="workspaceName" name="companyName" value="${w.companyName}" placeholder="مثال: وكالة نمو الرقمية" aria-invalid="${Boolean(state.onboardingErrors.companyName)}"/>${onboardingError("companyName")}</div><div class="form-field"><label for="workspaceIndustry">القطاع</label><select id="workspaceIndustry" name="industry"><option value="">اختر القطاع</option>${["وكالة تسويق","مبيعات الشركات","عيادة","عقار","شركة تقنية","خدمات","أخرى"].map(x=>`<option ${w.industry===x?"selected":""}>${x}</option>`).join("")}</select>${onboardingError("industry")}</div><div class="form-field"><label for="workspaceCity">المدينة</label><input id="workspaceCity" name="city" value="${w.city}" placeholder="مثال: الرياض"/>${onboardingError("city")}</div><div class="form-field wide"><label for="workspaceTeam">حجم الفريق</label><select id="workspaceTeam" name="teamSize"><option value="">اختر حجم الفريق</option>${["فردي","٢–٥","٦–١٠","١١–٢٥","أكثر من ٢٥"].map(x=>`<option ${w.teamSize===x?"selected":""}>${x}</option>`).join("")}</select>${onboardingError("teamSize")}</div></div><div class="wizard-actions"><span></span><button class="button primary" type="submit">التالي</button></div></form>`;
  if (step === 2) return `<form class="wizard-form" data-form="onboarding" data-step="2" novalidate><h1>ما الهدف الرئيسي من استخدام المنصة؟</h1><p>يمكنك اختيار أكثر من هدف. يساعدنا ذلك على ترتيب لوحة التجربة الأولية.</p><div class="onboarding-choice-grid">${[["discover","اكتشاف عملاء جدد"],["followup","تحسين متابعة العملاء"],["convert","زيادة التحويل"],["conversations","إدارة المحادثات"],["automation","أتمتة المتابعة"],["attribution","قياس الإيراد من المصادر"]].map(([v,l])=>onboardingChoice("goals",v,l)).join("")}</div>${onboardingError("goals")}<div class="wizard-actions"><button class="button" data-action="onboarding-back" type="button">السابق</button><button class="button primary" type="submit">التالي</button></div></form>`;
  if (step === 3) return `<form class="wizard-form" data-form="onboarding" data-step="3" novalidate><h1>من أين تحصل على العملاء الآن؟</h1><p>اختر المصادر التي تستخدمها حاليًا. جميع الخيارات في هذا النموذج تجريبية فقط.</p><div class="onboarding-choice-grid">${[["business","خرائط الأعمال ومصادر الشركات"],["file","ملفات البيانات والجداول"],["website","نماذج الموقع"],["whatsapp","واتساب"],["manual","إدخال يدوي"],["external-crm","نظام إدارة عملاء خارجي"]].map(([v,l])=>onboardingChoice("sources",v,l)).join("")}</div>${onboardingError("sources")}<div class="wizard-actions"><button class="button" data-action="onboarding-back" type="button">السابق</button><button class="button primary" type="submit">التالي</button></div></form>`;
  if (step === 4) return `<form class="wizard-form" data-form="onboarding" data-step="4" novalidate><h1>كيف يعمل فريق المبيعات؟</h1><p>تغذي هذه البيانات مؤشرات مساحة العمل التجريبية فقط.</p><div class="form-grid"><div class="form-field"><label for="salesTeam">عدد أعضاء الفريق</label><input id="salesTeam" name="salesTeam" class="ltr" inputmode="numeric" value="${w.salesTeam || ""}" placeholder="مثال: ٦"/>${onboardingError("salesTeam")}</div><div class="form-field"><label for="hasPipeline">هل يوجد مسار مبيعات؟</label><select id="hasPipeline" name="pipeline"><option value="">اختر الإجابة</option><option value="نعم" ${w.pipeline==="نعم"?"selected":""}>نعم</option><option value="لا" ${w.pipeline==="لا"?"selected":""}>لا</option></select>${onboardingError("pipeline")}</div><div class="form-field"><label for="monthlyLeads">متوسط العملاء شهريًا</label><input id="monthlyLeads" name="monthlyLeads" class="ltr" inputmode="numeric" value="${w.monthlyLeads}" placeholder="مثال: ٥٠٠"/>${onboardingError("monthlyLeads")}</div><div class="form-field"><label for="averageDealValue">متوسط قيمة الصفقة</label><input id="averageDealValue" name="averageDealValue" class="ltr" inputmode="numeric" value="${w.averageDealValue}" placeholder="مثال: ٢٥٠٠٠"/>${onboardingError("averageDealValue")}</div></div><div class="wizard-preview-metrics"><span>الفريق: <b>${w.salesTeam || "—"}</b></span><span>العملاء شهريًا: <b>${w.monthlyLeads || "—"}</b></span><span>متوسط الصفقة: <b>${w.averageDealValue ? `${w.averageDealValue} ر.س` : "—"}</b></span></div><div class="wizard-actions"><button class="button" data-action="onboarding-back" type="button">السابق</button><button class="button primary" type="submit">التالي</button></div></form>`;
  return `<form class="wizard-form" data-form="onboarding" data-step="5" novalidate><h1>كيف تريد أن يساعدك الذكاء الاصطناعي؟</h1><p>اختر التفضيلات التي تريد ظهورها في التجربة. يمكنك تغييرها لاحقًا.</p><div class="onboarding-choice-grid">${[["score","تقييم فرص العملاء"],["next-step","اقتراح الخطوة التالية"],["draft","صياغة الردود"],["summary","تلخيص المحادثات"],["qualify","تأهيل العملاء"],["follow","متابعة العملاء"]].map(([v,l])=>onboardingChoice("aiPreferences",v,l)).join("")}</div><div class="prototype-notice"><b>تنبيه تجريبي</b><span>جميع وظائف الذكاء الاصطناعي في هذا النموذج محاكاة لغرض اختبار تجربة المنتج فقط.</span></div><div class="wizard-actions"><button class="button" data-action="onboarding-back" type="button">السابق</button><div><button class="button ghost" data-action="onboarding-skip" type="button">تجاوز الآن</button><button class="button primary" type="submit">دخول مساحة العمل</button></div></div></form>`;
}
function renderOnboarding() { const stepNames=["الشركة","الهدف","المصادر","الفريق","الذكاء الاصطناعي"]; return `<div class="onboarding-shell"><aside class="onboarding-aside">${brand()}<div><p class="eyebrow">إعداد مساحة العمل</p><h2>ابدأ خلال خمس خطوات قصيرة.</h2><p>بعد الإعداد تدخل مباشرة إلى مساحة عمل تجريبية مبنية على اختياراتك.</p></div><ol class="onboarding-progress">${stepNames.map((name,index)=>`<li class="${index+1<state.onboardingStep?"done":index+1===state.onboardingStep?"active":""}" ${index+1===state.onboardingStep?"aria-current=\"step\"":""}><i>${index+1<state.onboardingStep?"✓":index+1}</i><span>${name}</span></li>`).join("")}</ol><small>لا يتم حفظ أي معلومات خارج الذاكرة الحالية للنموذج.</small></aside><main class="onboarding-main"><div class="onboarding-card"><div class="onboarding-step-count">الخطوة ${state.onboardingStep} من ٥</div>${renderOnboardingStep()}</div></main></div>`; }
function renderSidebar(route) { const workspaceMeta=state.workspace.companyName?`${state.workspace.companyName} · ${state.workspace.teamSize || "فريق جديد"}`:"مسؤولة النمو"; let lastGroup = null; return `<aside class="sidebar ${state.sidebarCollapsed ? "collapsed" : ""}" id="sidebar"><div class="sidebar-brand-row">${brand()}<button class="collapse-button" data-action="toggle-sidebar-collapse" aria-label="طي القائمة">›</button></div><nav class="sidebar-nav">${navItems.map(item => { let group = ""; if (item.group && item.group !== lastGroup) { group = `<p class="nav-group">${item.group}</p>`; lastGroup = item.group; } return `${group}<button class="side-link ${route === item.id ? "active" : ""}" title="${item.label}" data-route="${item.id}">${icon(item.icon)}<span>${item.label}</span>${item.id === "inbox" ? `<em class="nav-pill">${state.notifications}</em>` : ""}</button>`; }).join("")}</nav><div class="sidebar-bottom"><div class="usage-card"><span><b>رصيد الاكتشاف</b><b class="mono">1,240</b></span><div class="meter"><i></i></div><small>الباقة المهنية</small></div><button class="profile-trigger" data-action="open-profile"><i class="avatar">س</i><span><b>سارة العمري</b><small>${workspaceMeta}</small></span></button></div></aside>`; }
function renderTopbar(route) { const labels = Object.fromEntries(navItems.map(x=>[x.id,x.label])); const workspaceName=state.workspace.companyName || "مساحة العمل"; return `<header class="topbar"><div class="page-crumb"><button class="top-icon menu-button hidden" data-action="toggle-sidebar">☰</button><span>${workspaceName}</span><i>›</i><b>${labels[route] || "الرئيسية"}</b></div><label class="command-bar"><span>⌘</span><input id="commandInput" placeholder="ابحث في النظام أو اطلب إجراء..."/><kbd>⌘ K</kbd></label><div class="top-actions"><button class="button compact" data-action="route-discovery">اكتشاف جديد</button><button class="top-icon" data-action="toggle-theme" title="المظهر">◐</button><button class="top-icon" data-action="show-notifications" title="الإشعارات">◌</button></div></header>`; }
function renderApp(route) { return `<div class="app-shell ${state.sidebarCollapsed ? "sidebar-is-collapsed" : ""}">${renderSidebar(route)}<main class="workspace">${renderTopbar(route)}<div class="page-content" id="pageContent">${renderPage(route)}</div></main></div>`; }
function renderPage(route) { const ctx = { fmt, sar, button, pageHead, statusClass }; if (route === "dashboard") return renderDashboard(ctx); if (route === "ui-kit") return renderUiKit(ctx); return renderPlaceholder(route); }
function renderPlaceholder(route) { const item = navItems.find(x=>x.id===route); const title=item?.label || "هذه الشاشة"; const shipment=shipments[route] || "S1"; return `${pageHead("خريطة المنتج", title, `هذه واجهة مخططة ومثبتة معماريًا ضمن ${shipment}. سيبدأ تنفيذها بعد اعتماد CTO للشحنة المناسبة.`, button("العودة للرئيسية","route-dashboard","button primary"))}<section class="placeholder-card"><span>${shipment}</span><div><h2>${title}</h2><p>لا توجد وظيفة إنتاجية هنا في S0. المسار والتنقل والكيان الأساسي محفوظة في خريطة الشاشات ونموذج الكيانات.</p></div><button class="button" data-action="route-ui-kit">فتح مكتبة الواجهة</button></section>`; }
function render() { const route = getRoute(); document.documentElement.lang = "ar"; document.documentElement.dir = "rtl"; document.documentElement.dataset.theme = state.theme; if (route === "landing") app.innerHTML = renderLanding(); else if (route === "login") app.innerHTML = renderLogin(); else if (route === "onboarding") app.innerHTML = renderOnboarding(); else app.innerHTML = renderApp(route); bindEvents(); }
function syncOnboardingForm(form) { const data=new FormData(form); ["companyName","industry","city","teamSize","salesTeam","pipeline","monthlyLeads","averageDealValue"].forEach(key=>{if(data.has(key)) state.workspace[key]=String(data.get(key)).trim();}); }
function validateOnboardingStep(step) { const w=state.workspace; const errors={}; if(step===1){if(!w.companyName)errors.companyName="أدخل اسم الشركة للمتابعة.";if(!w.industry)errors.industry="اختر القطاع.";if(!w.city)errors.city="أدخل المدينة.";if(!w.teamSize)errors.teamSize="اختر حجم الفريق.";} if(step===2&&!w.goals.length)errors.goals="اختر هدفًا واحدًا على الأقل."; if(step===3&&!w.sources.length)errors.sources="اختر مصدرًا واحدًا على الأقل."; if(step===4){if(!w.salesTeam)errors.salesTeam="أدخل عدد أعضاء الفريق.";if(!w.pipeline)errors.pipeline="اختر حالة مسار المبيعات.";if(!w.monthlyLeads)errors.monthlyLeads="أدخل متوسط العملاء الشهري.";if(!w.averageDealValue)errors.averageDealValue="أدخل متوسط قيمة الصفقة.";} state.onboardingErrors=errors; return Object.keys(errors).length===0; }
function handleLogin(form) { const data=new FormData(form); const email=String(data.get("email")||"").trim(); const password=String(data.get("password")||"").trim(); const errors={}; if(!email)errors.email="أدخل البريد الإلكتروني.";else if(!/^\S+@\S+\.\S+$/.test(email))errors.email="أدخل بريدًا إلكترونيًا صحيحًا.";if(!password)errors.password="أدخل كلمة المرور.";state.loginErrors=errors;if(Object.keys(errors).length){render();return;} state.signedIn=true;toast("تم التحقق محليًا من بيانات الدخول التجريبية.","success");go(state.onboardingDone?"dashboard":"onboarding"); }
function handleOnboarding(form) { syncOnboardingForm(form); const step=Number(form.dataset.step); if(!validateOnboardingStep(step)){render();return;} if(step===5){finishOnboarding();return;} state.onboardingErrors={};state.onboardingStep=step+1;render(); }
function finishOnboarding() { state.onboardingDone=true;state.signedIn=true;state.onboardingErrors={};go("dashboard");toast("تم تجهيز مساحة العمل التجريبية وفق اختياراتك.","success"); }
function bindEvents() { document.querySelectorAll("[data-route]").forEach(el => el.addEventListener("click",()=>{if(el.dataset.business)state.selectedBusinessId=el.dataset.business;if(el.dataset.conversation)state.selectedConversationId=el.dataset.conversation;go(el.dataset.route);})); document.querySelectorAll("[data-action]").forEach(el => el.addEventListener("click",()=>handleAction(el.dataset.action, el.dataset))); document.querySelectorAll("[data-dashboard-time]").forEach(el=>el.addEventListener("click",()=>{state.dashboardTimeframe=el.dataset.dashboardTime;render();})); document.querySelectorAll("[data-dashboard-view]").forEach(el=>el.addEventListener("click",()=>{state.dashboardView=el.dataset.dashboardView;render();})); document.querySelectorAll("[data-onboarding-choice]").forEach(el=>el.addEventListener("click",()=>{const collection=el.dataset.onboardingChoice;const value=el.dataset.value;const selected=state.workspace[collection];state.workspace[collection]=selected.includes(value)?selected.filter(x=>x!==value):[...selected,value];delete state.onboardingErrors[collection];render();})); document.querySelectorAll("[data-form]").forEach(form => form.addEventListener("submit", event => { event.preventDefault(); if(form.dataset.form==="login")handleLogin(form);if(form.dataset.form==="onboarding")handleOnboarding(form); })); document.querySelector("#commandInput")?.addEventListener("keydown",e=>{if(e.key==="Enter"&&e.target.value.trim()){toast(`تم تسجيل طلب تجريبي: «${e.target.value.trim()}».`,"success");e.target.value="";}}); }
function handleAction(action, meta = {}) { if (action === "go-login") go("login"); else if (action === "go-onboarding") { state.onboardingStep=1;state.onboardingErrors={};go("onboarding"); } else if (action === "onboarding-back") { state.onboardingStep=Math.max(1,state.onboardingStep-1);state.onboardingErrors={};render(); } else if (action === "onboarding-skip") finishOnboarding(); else if (action.startsWith("route-")) go(action.replace("route-", "")); else if (action === "toggle-sidebar-collapse") { state.sidebarCollapsed=!state.sidebarCollapsed; render(); } else if (action === "toggle-theme") { state.theme = state.theme === "light" ? "dark" : "light"; render(); } else if (action === "toggle-sidebar") document.querySelector("#sidebar")?.classList.toggle("open"); else if (action === "scroll-workflow") document.querySelector("#workflow")?.scrollIntoView({behavior:"smooth"}); else if (action === "show-notifications") toast("لديك 3 تنبيهات تحتاج إلى مراجعة."); else if (action === "open-profile") toast("ملف سارة العمري — مسؤولة النمو."); else if (action === "show-ui-toast") toast("هذه رسالة حالة من مكتبة الواجهة الداخلية.","success"); else if (action === "show-landing-demo") toast("هذه معاينة ببيانات تجريبية تشرح طبقة التحليل وسير المبيعات."); else if (action === "create-followup") { if(meta.business)state.selectedBusinessId=meta.business;toast("تم إنشاء متابعة تجريبية مرتبطة بالعميل.","success"); } else if (action === "dashboard-ready") { state.dashboardView="ready";render(); } else if (action === "forgot-password") toast("استعادة كلمة المرور غير متاحة في النموذج التجريبي."); }
window.addEventListener("hashchange",render); window.addEventListener("keydown",event=>{ if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();document.querySelector("#commandInput")?.focus();} }); render();
