/* S9 visual reminder: Arabic RTL operational workspace. Automation is deterministic local simulation, never a scheduler, sender, or agent. */
import {
  appointmentLocationLabels, appointmentStatusLabels, appointmentTypeLabels, automationActionCatalog, automationActionStatusLabels,
  automationApprovalPolicies, automationRuleStatusLabels, automationRunStatusLabels, automationTriggerCatalog, getAppointment,
  getAppointments, getAutomationApprovalQueue, getAutomationMetrics, getAutomationRule, getAutomationRules, getAutomationRuns,
  getAutomationRunActionExecutions, getLead, getTasksWorkspace, mockModel, state
} from "./data.js";

const escapeHtml = (value) => String(value ?? "").replace(/[&<>'"]/g, (char) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" })[char]);
const formatDateTime = (value) => value ? new Intl.DateTimeFormat("ar-SA", { dateStyle:"medium", timeStyle:"short" }).format(new Date(value)) : "—";
const statusPill = (status, labels, tone = "") => `<span class="s9-status ${tone || status}">${labels[status] || status}</span>`;
const actionLabel = (type) => automationActionCatalog.find((item) => item.type === type)?.label || type;
const triggerLabel = (type) => automationTriggerCatalog.find((item) => item.id === type)?.label || type;
const userLabel = (id) => mockModel.users.find((user) => user.id === id)?.name || "—";

function renderDecisionRail(current = "القواعد") {
  const steps = [["1","الحدث"],["2","الشروط"],["3","القاعدة"],["4","الإجراء"],["5","الموافقة"],["6","التدقيق"]];
  return `<div class="s9-decision-rail" aria-label="سكة قرار الأتمتة">${steps.map(([num, label]) => `<span class="${label === current ? "active" : ""}"><i>${num}</i>${label}</span>`).join("<b></b>")}</div>`;
}

function ruleSentence(rule) {
  const group = mockModel.automationConditionGroups.find((item) => item.id === rule.conditionGroupId);
  const condition = group?.conditions?.[0];
  const conditionText = condition ? `إذا كان ${condition.field.replace("lead.", "العميل ").replace("deal.", "الصفقة ").replace("conversation.", "المحادثة ")} ${condition.operator === "equals" ? "يساوي" : condition.operator === "not_equals" ? "لا يساوي" : condition.operator} ${condition.value}` : "من دون شرط إضافي";
  const actions = rule.actionIds.map((id) => actionLabel(mockModel.automationActions.find((item) => item.id === id)?.type)).join("، ");
  return `عندما ${triggerLabel(rule.triggerType)}، ${conditionText}، ${actions}.`;
}

function renderRuleCard(rule) {
  const runs = getAutomationRuns(rule.id);
  const lastRun = runs[0];
  return `<article class="s9-rule-card">
    <header><div><span class="mono">${rule.id}</span><h3>${escapeHtml(rule.name)}</h3></div>${statusPill(rule.status, automationRuleStatusLabels)}</header>
    <p class="s9-rule-sentence">${escapeHtml(ruleSentence(rule))}</p>
    <dl><div><dt>المشغّل</dt><dd>${triggerLabel(rule.triggerType)}</dd></div><div><dt>السياسة</dt><dd>${rule.approvalPolicy === "auto_safe" ? "آمن تلقائيًا" : rule.approvalPolicy === "approval_required" ? "تحتاج موافقة" : "يدوي فقط"}</dd></div><div><dt>آخر تشغيل</dt><dd>${lastRun ? `${statusPill(lastRun.status, automationRunStatusLabels)} ${formatDateTime(lastRun.createdAt)}` : "لم تشغّل بعد"}</dd></div></dl>
    <footer><span>${rule.actionIds.length} إجراء</span><div><button class="button compact" data-s9-action="test-rule" data-rule-id="${rule.id}">اختبار القاعدة</button><button class="button compact" data-s9-action="open-rule" data-rule-id="${rule.id}">التفاصيل</button><button class="button compact" data-s9-action="toggle-rule" data-rule-id="${rule.id}">${rule.status === "enabled" ? "تعطيل" : "تفعيل"}</button></div></footer>
  </article>`;
}

function renderApprovalQueue() {
  const queue = getAutomationApprovalQueue();
  return `<section class="s9-panel s9-approval-panel"><header class="s9-panel-head"><div><p class="eyebrow">طابور الموافقات</p><h2>إجراءات تنتظر قرارًا بشريًا</h2></div><span class="s9-count">${queue.length}</span></header>${queue.length ? `<div class="s9-approval-list">${queue.map((execution) => { const run = getAutomationRuns().find((item) => item.id === execution.automationRunId); const lead = run && getLead(run.triggerEntityType === "lead" ? run.triggerEntityId : (run.triggerEntityType === "conversation" ? mockModel.conversations.find((item) => item.id === run.triggerEntityId)?.leadId : mockModel.deals.find((item) => item.id === run.triggerEntityId)?.leadId)); return `<article><div><span class="mono">${execution.id}</span><h3>${actionLabel(execution.actionType)}</h3><p>${run?.ruleNameSnapshot || "قاعدة غير متاحة"} · ${lead?.id || "—"}</p><small>البيانات المقترحة: ${escapeHtml(JSON.stringify(execution.payload))}</small></div><div class="s9-approval-actions"><button class="button compact" data-s9-action="reject-action" data-execution-id="${execution.id}">رفض</button><button class="button primary compact" data-s9-action="approve-action" data-execution-id="${execution.id}">موافقة وتنفيذ</button></div></article>`; }).join("")}</div>` : `<div class="s9-empty"><b>لا توجد إجراءات معلقة</b><p>الإجراءات الحساسة تظهر هنا قبل أي mutation محلية.</p></div>`}</section>`;
}

function renderAuditLog(ruleId = null) {
  const runs = getAutomationRuns(ruleId);
  return `<section class="s9-panel s9-audit"><header class="s9-panel-head"><div><p class="eyebrow">سجل التدقيق</p><h2>من الحدث إلى النتيجة</h2></div><span>${runs.length} تشغيل</span></header><div class="s9-audit-list">${runs.map((run) => { const executions = getAutomationRunActionExecutions(run.id); return `<article class="s9-audit-run"><div class="s9-audit-trace"><span class="mono">${run.id}</span>${statusPill(run.status, automationRunStatusLabels)}<b>${escapeHtml(run.ruleNameSnapshot)}</b><small>${run.triggerEventType} → ${run.triggerEntityId}</small></div><div class="s9-audit-flow"><span>الحدث: ${formatDateTime(run.triggeredAt)}</span><span>الشروط: ${run.matchedConditions ? "مطابقة" : "غير مطابقة"}</span>${executions.map((execution) => `<span>${actionLabel(execution.actionType)}: ${statusPill(execution.status, automationActionStatusLabels)}</span>`).join("")}${run.failureReason ? `<span class="s9-failure">${escapeHtml(run.failureReason)}</span>` : ""}</div><footer><span>الإصدار ${run.automationRuleVersion}</span><span>${run.origin === "automation" ? "منع loop guard" : "محاكاة محلية"}</span></footer></article>`; }).join("") || `<div class="s9-empty"><b>لا يوجد سجل بعد</b><p>شغّل قاعدة أو استخدم الاختبار الجاف لمراجعة المسار.</p></div>`}</div></section>`;
}

export function renderAutomation(ctx, ruleId = null) {
  const metrics = getAutomationMetrics();
  const rules = getAutomationRules();
  const selected = ruleId ? getAutomationRule(ruleId) : getAutomationRule(state.selectedAutomationId);
  return `${ctx.pageHead("S9 · محاكاة محلية", "الأتمتة", "حوّل حدثًا معروفًا إلى مهمة أو اقتراح خاضع للسياسة. لا توجد جدولة خلفية أو إرسال خارجي.", `<button class="button" data-s9-action="open-rule-form">قاعدة جديدة</button>`)}
    ${renderDecisionRail()}
    <section class="s9-metrics">${[[metrics.totalRules,"إجمالي القواعد","قواعد محلية"],[metrics.enabled,"قواعد مفعلة","تُقيّم عند التشغيل"],[metrics.runsToday,"تشغيلات اليوم","من سجل Runs"],[metrics.awaitingApproval,"تحتاج موافقة","لا mutation قبل القرار"],[metrics.failed,"فشل مضبوط","مكشوف في السجل"]].map(([value,label,note])=>`<article><b>${value}</b><span>${label}</span><small>${note}</small></article>`).join("")}</section>
    <section class="s9-builder-strip"><div><p class="eyebrow">No-code workflow</p><h2>عندما يحدث… إذا… افعل…</h2><p>تقرأ القاعدة سياق الحدث فقط، ثم تطبق سياسة تنفيذ مركزية قبل أي إجراء.</p></div><button class="button primary" data-s9-action="open-rule-form">إنشاء قاعدة</button></section>
    <section class="s9-rule-layout"><div class="s9-rule-list"><header><h2>القواعد</h2><div class="s9-filter-row"><input data-s9-filter="automation-search" value="${escapeHtml(state.automationFilters.search)}" placeholder="ابحث في القواعد"/><select data-s9-filter="automation-status"><option value="all">كل الحالات</option>${Object.entries(automationRuleStatusLabels).map(([id,label])=>`<option value="${id}" ${state.automationFilters.status===id?"selected":""}>${label}</option>`).join("")}</select></div></header>${rules.map(renderRuleCard).join("")}</div><aside class="s9-rule-detail">${selected ? `<p class="eyebrow">تفاصيل القاعدة</p><h2>${escapeHtml(selected.name)}</h2><p>${escapeHtml(ruleSentence(selected))}</p><dl><div><dt>المعرّف</dt><dd class="mono">${selected.id}</dd></div><div><dt>الإصدار</dt><dd>${selected.version}</dd></div><div><dt>آخر تعديل</dt><dd>${formatDateTime(selected.updatedAt)}</dd></div></dl><div class="s9-detail-actions"><button class="button" data-s9-action="test-rule" data-rule-id="${selected.id}">اختبار جاف</button>${selected.triggerType === "manual" ? `<button class="button primary" data-s9-action="run-rule" data-rule-id="${selected.id}">تشغيل الآن</button>` : ""}</div>` : `<div class="s9-empty">اختر قاعدة لعرض تفاصيلها.</div>`}</aside></section>
    ${renderApprovalQueue()}${renderAuditLog(ruleId)}`;
}

function taskOrigin(task) { return task.createdByAutomationRunId ? "automation" : "manual"; }
export function renderTasksWorkspace(ctx) {
  const rows = getTasksWorkspace();
  return `${ctx.pageHead("S9 · Tasks", "المهام", "سجل واحد للمهام اليدوية والآلية. تعتمد كل مهمة على عقد S5 نفسه.", "")}
  <section class="s9-panel"><div class="s9-filter-row"><input data-s9-filter="task-search" value="${escapeHtml(state.taskFilters.search)}" placeholder="ابحث بعنوان المهمة أو المعرّف"/><select data-s9-filter="task-status"><option value="all">كل الحالات</option>${[["pending","قيد الانتظار"],["overdue","متأخرة"],["completed","مكتملة"]].map(([id,label])=>`<option value="${id}" ${state.taskFilters.status===id?"selected":""}>${label}</option>`).join("")}</select><select data-s9-filter="task-origin"><option value="all">كل المصادر</option><option value="automation" ${state.taskFilters.origin==="automation"?"selected":""}>أنشأتها أتمتة</option><option value="manual" ${state.taskFilters.origin==="manual"?"selected":""}>يدوية</option></select><select data-s9-filter="task-due"><option value="all">كل المواعيد</option><option value="overdue">متأخرة</option><option value="today">اليوم</option><option value="upcoming">قادمة</option></select></div><div class="s9-table-wrap"><table class="s9-table"><thead><tr><th>المهمة</th><th>العميل</th><th>المالك</th><th>الحالة</th><th>الاستحقاق</th><th>المصدر</th><th></th></tr></thead><tbody>${rows.map((task)=>{ const lead=getLead(task.leadId); return `<tr><td><b>${escapeHtml(task.title)}</b><small class="mono">${task.id}</small></td><td>${lead?.id || "—"}</td><td>${userLabel(task.ownerId)}</td><td>${task.status}</td><td>${formatDateTime(task.dueAt)}</td><td>${taskOrigin(task)==="automation"?`<span class="s9-origin">أتمتة ${task.createdByAutomationRunId}</span>`:"يدوي"}</td><td>${task.status !== "completed" ? `<button class="button compact" data-crm-action="complete-task" data-task="${task.id}">إكمال</button>`:""}</td></tr>`; }).join("") || `<tr><td colspan="7">لا توجد مهام مطابقة.</td></tr>`}</tbody></table></div></section>`;
}

export function renderAppointmentsWorkspace(ctx) {
  const appointments = getAppointments();
  return `${ctx.pageHead("S9 · Appointments", "المواعيد", "مواعيد محلية قابلة للمراجعة؛ لا يوجد تقويم خارجي أو مزامنة.", `<button class="button primary" data-s9-action="open-appointment-form">موعد جديد</button>`)}
  <section class="s9-panel"><div class="s9-filter-row"><select data-s9-filter="appointment-status"><option value="all">كل الحالات</option>${Object.entries(appointmentStatusLabels).map(([id,label])=>`<option value="${id}" ${state.appointmentFilters.status===id?"selected":""}>${label}</option>`).join("")}</select><select data-s9-filter="appointment-owner"><option value="all">كل المالكين</option>${mockModel.users.map((user)=>`<option value="${user.id}" ${state.appointmentFilters.ownerId===user.id?"selected":""}>${user.name}</option>`).join("")}</select><select data-s9-filter="appointment-type"><option value="all">كل الأنواع</option>${Object.entries(appointmentTypeLabels).map(([id,label])=>`<option value="${id}" ${state.appointmentFilters.type===id?"selected":""}>${label}</option>`).join("")}</select></div><div class="s9-appointment-list">${appointments.map((appointment)=>{ const lead=getLead(appointment.leadId); return `<article><div class="s9-appointment-time"><b>${formatDateTime(appointment.startsAt)}</b><small>حتى ${formatDateTime(appointment.endsAt)}</small></div><div><h3>${escapeHtml(appointment.title)}</h3><p>${lead?.id || "—"} · ${userLabel(appointment.ownerId)} · ${appointmentTypeLabels[appointment.type]}</p><small>${appointmentLocationLabels[appointment.locationType]} · ${escapeHtml(appointment.location)}</small></div><aside>${statusPill(appointment.status, appointmentStatusLabels)}${appointment.createdByAutomationRunId ? `<span class="s9-origin">أتمتة ${appointment.createdByAutomationRunId}</span>` : ""}${appointment.overlapWarning ? `<span class="s9-warning">تداخل محتمل</span>` : ""}</aside></article>`; }).join("") || `<div class="s9-empty">لا توجد مواعيد مطابقة.</div>`}</div></section>`;
}

function renderRuleForm() {
  return `<div class="s9-modal-backdrop" data-s9-action="close-modal"><section class="s9-modal" role="dialog" aria-modal="true" aria-labelledby="s9RuleTitle"><header><div><p class="eyebrow">قاعدة جديدة</p><h2 id="s9RuleTitle">عندما يحدث… إذا… افعل…</h2></div><button class="modal-close" data-s9-action="close-modal" aria-label="إغلاق">×</button></header><form data-s9-form="create-rule"><div class="form-grid"><label class="form-field wide">اسم الأتمتة<input name="name" required placeholder="مثال: متابعة عميل جديد"/></label><label class="form-field"><span>عندما يحدث</span><select name="triggerType" required>${automationTriggerCatalog.map((trigger)=>`<option value="${trigger.id}">${trigger.label}</option>`).join("")}</select></label><label class="form-field"><span>إذا كان الحقل</span><select name="conditionField"><option value="lead.priority">أولوية العميل</option><option value="lead.status">حالة العميل</option><option value="conversation.needs_reply">المحادثة تحتاج ردًا</option><option value="deal.stage">مرحلة الصفقة</option></select></label><label class="form-field"><span>المعامل</span><select name="conditionOperator"><option value="equals">يساوي</option><option value="not_equals">لا يساوي</option><option value="is_known">معلوم</option><option value="is_unknown">غير معلوم</option></select></label><label class="form-field"><span>القيمة</span><input name="conditionValue" value="high" placeholder="high"/></label><label class="form-field"><span>افعل</span><select name="actionType">${automationActionCatalog.map((action)=>`<option value="${action.id}">${action.label}</option>`).join("")}</select></label><label class="form-field"><span>سياسة الموافقة</span><select name="approvalPolicy"><option value="auto_safe">آمن تلقائيًا</option><option value="approval_required">تحتاج موافقة</option><option value="manual_only">يدوي فقط</option></select></label><label class="form-field"><span>الحالة</span><select name="status"><option value="draft">مسودة</option><option value="enabled">مفعلة</option></select></label></div><div class="s9-preview"><b>معاينة القاعدة</b><p>عندما يحدث الحدث المحدد، يقيّم النظام الشرط محليًا ثم ينشئ الإجراء وفق السياسة المختارة.</p></div><footer><button class="button" type="button" data-s9-action="close-modal">إلغاء</button><button class="button primary" type="submit">حفظ القاعدة</button></footer></form></section></div>`;
}

function renderAppointmentForm() {
  return `<div class="s9-modal-backdrop" data-s9-action="close-appointment-modal"><section class="s9-modal" role="dialog" aria-modal="true" aria-labelledby="s9AppointmentTitle"><header><div><p class="eyebrow">موعد محلي</p><h2 id="s9AppointmentTitle">إنشاء موعد</h2></div><button class="modal-close" data-s9-action="close-appointment-modal" aria-label="إغلاق">×</button></header><form data-s9-form="create-appointment"><div class="form-grid"><label class="form-field wide">العنوان<input name="title" required placeholder="مثال: مراجعة العرض"/></label><label class="form-field"><span>العميل</span><select name="leadId">${mockModel.leads.map((lead)=>`<option value="${lead.id}">${lead.id}</option>`).join("")}</select></label><label class="form-field"><span>المالك</span><select name="ownerId">${mockModel.users.map((user)=>`<option value="${user.id}">${user.name}</option>`).join("")}</select></label><label class="form-field"><span>يبدأ</span><input name="startsAt" type="datetime-local" required value="2026-08-16T11:00"/></label><label class="form-field"><span>ينتهي</span><input name="endsAt" type="datetime-local" required value="2026-08-16T11:30"/></label><label class="form-field"><span>النوع</span><select name="type">${Object.entries(appointmentTypeLabels).map(([id,label])=>`<option value="${id}">${label}</option>`).join("")}</select></label><label class="form-field"><span>المكان</span><select name="locationType">${Object.entries(appointmentLocationLabels).map(([id,label])=>`<option value="${id}">${label}</option>`).join("")}</select></label><label class="form-field wide">الوصف المحلي<input name="location" value="رابط تجريبي محلي"/></label></div><footer><button class="button" type="button" data-s9-action="close-appointment-modal">إلغاء</button><button class="button primary" type="submit">إنشاء الموعد</button></footer></form></section></div>`;
}

export function renderAutomationModal() { return state.automationModal?.type === "create-rule" ? renderRuleForm() : ""; }
export function renderAppointmentModal() { return state.appointmentModal?.type === "create-appointment" ? renderAppointmentForm() : ""; }
