import { businesses, conversations, dashboardData, jobs, state } from "./data.js";

export function renderDashboard(ctx) {
  const { fmt, button } = ctx;
  const money = (value) => `${fmt(value)} ر.س`;
  const data = dashboardData;
  const business = (id) => businesses.find((item) => item.id === id);
  const maxFunnel = data.funnelMetrics[0].value;

  const stateSwitcher = `<section class="dashboard-state-panel" aria-label="حالات عرض لوحة التحكم"><span>حالات اختبار الواجهة:</span><div>${[["ready","مكتمل"],["loading","تحميل"],["empty","فارغ"],["error","خطأ"]].map(([id,label])=>`<button type="button" class="${state.dashboardView===id?"active":""}" data-dashboard-view="${id}">${label}</button>`).join("")}</div></section>`;
  if (state.dashboardView !== "ready") {
    const configurations = {
      loading: ["تحميل", "يتم تجهيز ملخص الأداء التجريبي…", "↻", "loading"],
      empty: ["لا توجد بيانات كافية بعد", "ابدأ أول عملية اكتشاف لبناء لوحة الأداء ومسار المتابعة.", "○", "empty"],
      error: ["تعذر عرض الملخص التجريبي", "هذه حالة واجهة مخصصة للفحص فقط، ويمكن العودة إلى البيانات التجريبية.", "!", "error"]
    };
    const [title, description, icon, kind] = configurations[state.dashboardView];
    return `<div class="exec-dashboard">${stateSwitcher}<section class="dashboard-feedback ${kind}"><i>${icon}</i><h2>${title}</h2><p>${description}</p>${state.dashboardView === "empty" ? button("اكتشاف عملاء", "route-discovery", "button primary") : button("العودة إلى الملخص", "dashboard-ready", "button primary")}</section></div>`;
  }

  return `<div class="exec-dashboard">
    <section class="decision-rail" aria-label="مسار القرار"><div class="decision-brand"><img src="/manus-storage/leadflow-orbit-mark_f6c27956.png" alt="نمو"/>مسار القرار</div><div class="decision-steps"><span class="done"><i>١</i><b>اكتشاف</b></span><span class="done"><i>٢</i><b>فهم</b></span><span class="done"><i>٣</i><b>تواصل</b></span><span class="active"><i>٤</i><b>قرار</b></span><span><i>٥</i><b>إيراد</b></span></div><small>ملخص تنفيذي</small></section>
    <header class="exec-header"><div><p class="eyebrow">الرئيسية</p><h1>ملخص أداء المبيعات واكتشاف العملاء اليوم</h1><p>هذه لوحة قيادة تجريبية تضع الفرص والقرارات ومصدر الإيراد في سياق واحد قابل للمراجعة.</p></div><div class="exec-header-actions"><div class="time-filter" aria-label="الفترة الزمنية">${["اليوم","7 أيام","30 يومًا","هذا الربع"].map(label=>`<button type="button" class="${state.dashboardTimeframe===label?"active":""}" data-dashboard-time="${label}">${label}</button>`).join("")}</div>${button("اكتشاف عملاء جدد", "route-discovery", "button primary")}<span class="exec-meta"><i></i>آخر تحديث تجريبي الآن</span></div></header>
    <div class="mock-strip"><b>بيانات تجريبية</b><span>جميع المؤشرات والأرقام في هذا السطح محاكاة لغرض اختبار تجربة المنتج وليست بيانات إنتاج.</span></div>
    ${stateSwitcher}
    <section class="exec-kpi-grid" aria-label="مؤشرات الأداء الرئيسية">${data.dashboardMetrics.map(metric=>`<article class="metric-card tone-${metric.tone}"><span>${metric.label}</span><b>${metric.format === "sar" ? money(metric.value) : fmt(metric.value)}</b><small class="metric-trend">${metric.trend}</small><div class="metric-foot"><i></i>${metric.note}</div></article>`).join("")}</section>
    <section class="executive-pair">
      <article class="card"><header class="card-head"><div><h2>يحتاج انتباهك</h2><p>عناصر محدودة تحتاج قرارًا أو متابعة من الفريق.</p></div></header><div class="attention-list">${data.attentionItems.map((item,index)=>`<article class="attention-item"><i class="attention-mark ${item.tone}">${String(index+1).padStart(2,"0")}</i><div><b>${item.title}</b><small>${item.description}</small></div><button type="button" class="button ghost" data-route="${item.route}">${item.action}</button></article>`).join("")}</div></article>
      <article class="card"><header class="card-head"><div><h2>توصيات الذكاء الاصطناعي</h2><p>توصيات قابلة للتنفيذ وليست نافذة محادثة.</p></div></header><div class="ai-recommendation-list">${data.aiRecommendations.map(recommendation=>{const related=business(recommendation.businessId);return `<article class="ai-recommendation"><header><span>${recommendation.kind}</span>${recommendation.score ? `<em class="score-inline">${recommendation.score}/100</em>` : ""}</header><b>${recommendation.title}</b><p>${recommendation.reason}</p><small>${recommendation.action}</small><footer><button type="button" class="button compact primary" data-route="${recommendation.primaryRoute}" ${related?`data-business="${related.id}"`:""}>${recommendation.primary}</button>${recommendation.secondary ? `<button type="button" class="button compact" data-action="${recommendation.secondaryAction}" data-business="${recommendation.businessId}">${recommendation.secondary}</button>` : ""}</footer></article>`;}).join("")}</div></article>
    </section>
    <section class="card"><header class="card-head"><div><h2>من الاكتشاف إلى الإيراد</h2><p>قمع تجريبي يوضح نسبة الانتقال بين مراحل رحلة اكتساب العميل والمبيعات.</p></div><button type="button" class="button ghost" data-route="analytics">عرض التحليل</button></header><div class="funnel-exec">${data.funnelMetrics.map((stage,index)=>`<article class="funnel-stage-exec"><span>${stage.label}</span><b>${fmt(stage.value)}</b>${index ? `<small>${stage.rate}% انتقال من المرحلة السابقة</small>` : `<small>نقطة بداية القمع</small>`}<i style="width:${Math.max(14,Math.round(stage.value/maxFunnel*100))}%"></i></article>`).join("")}</div></section>
    <section class="executive-pair">
      <article class="card"><header class="card-head"><div><h2>ملخص Pipeline</h2><p>قيمة الصفقات المفتوحة موزعة على المراحل الست الحالية.</p></div><button type="button" class="button ghost" data-route="pipeline">فتح المسار</button></header><div class="pipeline-summary">${data.pipelineSummary.map(stage=>`<button type="button" data-route="${stage.route}"><span>${stage.stage}</span><b>${fmt(stage.count)} صفقة</b><small>${money(stage.value)}</small><i style="--share:${stage.share}%"></i></button>`).join("")}</div></article>
      <article class="card"><header class="card-head"><div><h2>أفضل مصادر العملاء</h2><p>توزيع تجريبي للعملاء المؤهلين حسب المصدر.</p></div><button type="button" class="button ghost" data-route="analytics">تفاصيل المصدر</button></header><div class="source-performance">${data.sourcePerformance.map(source=>`<div class="source-bar ${source.tone}"><div><span>${source.source}</span><i style="--source:${source.value}%"><b></b></i></div><strong>${source.value}%</strong></div>`).join("")}</div></article>
    </section>
    <section class="executive-pair">
      <article class="card"><header class="card-head"><div><h2>صفقات قريبة من الإغلاق</h2><p>ثلاث صفقات تحتاج خطوة واضحة لتقليل وقت الإغلاق.</p></div><button type="button" class="button ghost" data-route="deals">كل الصفقات</button></header><div class="table-wrap"><table class="data-table deal-focus-table"><thead><tr><th>الصفقة</th><th>المرحلة</th><th>القيمة</th><th>الاحتمال</th><th>آخر نشاط</th><th>الإجراء التالي</th></tr></thead><tbody>${data.nearClosingDeals.map(deal=>{const item=business(deal.businessId);return `<tr><td><button type="button" data-route="lead-profile" data-business="${deal.businessId}">${item?.short || item?.name || deal.id}<small class="mono">${deal.id}</small></button></td><td><span class="status contact">${deal.stage}</span></td><td>${money(deal.value)}</td><td><b class="probability">${deal.probability}%</b></td><td>${deal.lastActivity}</td><td><small>${deal.nextAction}</small></td></tr>`;}).join("")}</tbody></table></div></article>
      <article class="card"><header class="card-head"><div><h2>أداء الاكتشاف</h2><p>تنتقل نتائج البحث التجريبية إلى مؤشرات تأهيل وCRM واضحة.</p></div><button type="button" class="button ghost" data-route="discovery">اكتشاف جديد</button></header><div class="table-wrap"><table class="data-table"><thead><tr><th>العملية</th><th>المصدر</th><th>الموقع</th><th>مكتشف</th><th>درجة عالية</th><th>أضيف إلى CRM</th><th>مؤهل</th><th>الحالة</th></tr></thead><tbody>${jobs.slice(0,3).map(job=>`<tr><td class="mono">${job.id}<small>${job.keyword}</small></td><td>${job.source}</td><td>${job.location}</td><td>${fmt(job.current)}</td><td>${fmt(job.highScore)}</td><td>${fmt(job.crmAdded)}</td><td>${fmt(job.qualified)}</td><td><span class="status ${job.status === "completed" ? "qualified" : "contact"}">${job.status === "completed" ? "مكتمل" : "قيد المعالجة"}</span></td></tr>`).join("")}</tbody></table></div></article>
    </section>
    <section class="executive-pair">
      <article class="card"><header class="card-head"><div><h2>المتابعات القادمة</h2><p>قائمة قصيرة تربط المهمة بسجل العميل والإجراء التالي.</p></div><button type="button" class="button ghost" data-route="tasks">كل المهام</button></header><div class="mini-list">${data.upcomingActivities.map(activity=>{const item=business(activity.businessId);const className=activity.status === "متأخر" ? "overdue" : activity.status === "اليوم" ? "today" : "upcoming";return `<button type="button" class="mini-list-item" data-route="${activity.route}" data-business="${activity.businessId}"><i class="list-icon">${activity.type.slice(0,1)}</i><div><b>${activity.title}</b><small>${item?.short || item?.name || "عميل تجريبي"} · ${activity.type}</small></div><span><em class="activity-status ${className}">${activity.status}</em><small>${activity.when}</small></span></button>`;}).join("")}</div></article>
      <article class="card"><header class="card-head"><div><h2>آخر المحادثات</h2><p>السياق التجاري بجانب القناة وليس رسالة معزولة.</p></div><button type="button" class="button ghost" data-route="inbox">فتح صندوق الوارد</button></header><div class="mini-list">${conversations.slice(0,4).map(conversation=>{const item=business(conversation.businessId);return `<button type="button" class="mini-list-item" data-route="inbox" data-conversation="${conversation.id}"><i class="list-icon">${conversation.channel.slice(0,1)}</i><div><b>${item?.short || item?.name || conversation.contact}</b><small>${conversation.preview}</small></div><span>${conversation.time}</span></button>`;}).join("")}</div></article>
    </section>
    <section class="card"><header class="card-head"><div><h2>ملخص الإيراد</h2><p>طبقة موجزة لتقدير حركة الإيراد وقيمة الفرص المفتوحة.</p></div><button type="button" class="button ghost" data-route="analytics">تحليل الإيراد</button></header><div class="revenue-summary"><div><span>الإيراد هذا الشهر</span><b>${money(data.revenueSummary.revenue)}</b></div><div><span>قيمة Pipeline</span><b>${money(data.revenueSummary.pipeline)}</b></div><div><span>متوسط الصفقة</span><b>${money(data.revenueSummary.averageDeal)}</b></div><div><span>معدل الفوز</span><b>${data.revenueSummary.winRate}%</b></div><div><span>متوسط دورة البيع</span><b>${data.revenueSummary.averageCycle}</b></div></div></section>
    <section class="card"><header class="card-head"><div><h2>من أين جاء الإيراد؟</h2><p>لقطة إسناد تربط الإيراد بعملية الاكتشاف الأصلية داخل هذا النموذج التجريبي.</p></div><button type="button" class="button ghost" data-route="analytics">عرض الإسناد</button></header><div class="attribution-snapshot">${data.attributionSummary.map(source=>`<article class="attribution-source"><h3>${source.label}</h3><dl><div><dt>عملية البحث</dt><dd>${source.jobId}</dd></div><div><dt>مكتشف</dt><dd>${fmt(source.discovered)}</dd></div><div><dt>مؤهل</dt><dd>${fmt(source.qualified)}</dd></div><div><dt>رابح</dt><dd>${fmt(source.won)}</dd></div></dl><footer><span>الإيراد المنسوب</span><b>${money(source.revenue)}</b></footer></article>`).join("")}</div></section>
  </div>`;
}
