// Design reminder: Dashboard is an operational command center, not a wall of decorative cards. It exposes the connected acquisition-to-revenue flow.
import { businesses, activities, conversations, jobs, metrics } from "./data.js";

export function renderDashboard(ctx) {
  const { fmt, sar, button, pageHead, statusClass } = ctx;
  const metricCards = [
    ["إجمالي العملاء المحتملين", fmt(metrics.totalLeads), "من مصادر الاكتشاف", ""],
    ["فرص عالية", fmt(metrics.highOpportunity), "+12.4% هذا الأسبوع", ""],
    ["تم التواصل", fmt(metrics.contacted), "30.8% من الإجمالي", ""],
    ["تم التأهيل", fmt(metrics.qualified), "+8.1% هذا الأسبوع", ""],
    ["الصفقات المفتوحة", fmt(metrics.openDeals), sar(metrics.pipelineValue), ""],
    ["إيراد هذا الشهر", sar(metrics.wonMonth), "+18.6% عن الشهر السابق", "highlight"],
    ["إيراد متأثر بالذكاء", sar(metrics.aiRevenue), "ضمن 67 محادثة", ""],
  ];
  return `${pageHead("لوحة التنفيذ", "صباح الخير، سارة", "هذه هي الصورة الحالية لرحلة الاكتساب والمبيعات — من عمليات البحث الجديدة إلى الإيراد المنسوب.", button("ابدأ اكتشافًا جديدًا", "route-discovery", "button primary"))}
  <section class="welcome-strip"><div><h2>قصة العرض الجاهزة: عيادات أسنان في الرياض</h2><p>ابدأ من الاكتشاف، ثم اختر عيادة ذات فرصة عالية وتابع رحلتها حتى الصفقة والإيراد.</p></div>${button("فتح رحلة العرض", "start-demo", "button primary")}</section>
  <section class="stats-grid">${metricCards.map(([label,value,sub,cls])=>`<article class="metric-card ${cls}"><span>${label}</span><b>${value}</b><small class="${sub.startsWith("+") ? "" : ""}">↗ ${sub}</small></article>`).join("")}</section>
  <section class="dashboard-grid">
    <article class="card"><header class="card-head"><div><h2>قمع اكتساب العملاء</h2><p>كيف تنتقل النتائج من مصدرها إلى صفقة رابحة</p></div><button class="button ghost" data-route="analytics">عرض التحليل</button></header><div class="funnel">${[["مكتشف",12480,100],["مُثرى",10250,82],["مؤهل",3820,61],["تم التواصل",2940,47],["فرصة",1120,31],["رابح",284,16]].map(([n,v,w])=>`<div class="funnel-row"><span>${n}</span><div class="funnel-bar"><i style="width:${w}%"></i></div><b>${fmt(v)}</b></div>`).join("")}</div></article>
    <article class="card"><header class="card-head"><div><h2>متابعة اليوم</h2><p>أنشطة مرتبطة بعملاء حقيقيين داخل النموذج</p></div><button class="button ghost" data-route="tasks">كل المهام</button></header><div class="mini-list">${activities.map(a=>{const b=businesses.find(x=>x.id===a.businessId);return `<button class="mini-list-item" data-route="lead-profile" data-business="${a.businessId}"><i class="list-icon">${a.type.slice(0,1)}</i><div><b>${a.title}</b><small>${b?.name}</small></div><span>${a.when}</span></button>`}).join("")}</div></article>
  </section>
  <section class="grid grid-main-side" style="margin-top:16px"><article class="card"><header class="card-head"><div><h2>عمليات بحث حديثة</h2><p>كل عملية بحث تبقى مرتبطة بالعملاء الناتجين عنها</p></div><button class="button ghost" data-route="discovery">اكتشاف جديد</button></header><div class="table-wrap"><table class="data-table"><thead><tr><th>رقم العملية</th><th>البحث</th><th>الموقع</th><th>النتائج</th><th>الحالة</th><th></th></tr></thead><tbody>${jobs.map(job=>`<tr><td class="mono">${job.id}</td><td>${job.keyword}</td><td>${job.location}</td><td>${fmt(job.current)} / ${fmt(job.total)}</td><td><span class="status ${job.status === "completed" ? "qualified" : "contact"}">${job.status === "completed" ? "مكتمل" : "قيد المعالجة"}</span></td><td>${button("فتح",job.status === "completed" ? "route-results" : "route-discovery-jobs","button ghost")}</td></tr>`).join("")}</tbody></table></div></article>
  <article class="card"><header class="card-head"><div><h2>ترشيحات الذكاء</h2><p>أفضل فرص يمكن لفريقك تحريكها</p></div></header><div class="mini-list">${businesses.slice(0,3).map(b=>`<button class="mini-list-item" data-route="intelligence" data-business="${b.id}"><i class="list-icon">${b.score}</i><div><b>${b.short}</b><small>${b.opportunity}</small></div><span class="score high">${b.score}</span></button>`).join("")}</div></article></section>
  <section class="grid grid-2" style="margin-top:16px"><article class="card"><header class="card-head"><div><h2>محادثات حديثة</h2><p>لا تظهر الرسالة وحدها؛ يظهر سياق العميل معها</p></div><button class="button ghost" data-route="inbox">فتح صندوق الوارد</button></header><div class="mini-list">${conversations.map(c=>{const b=businesses.find(x=>x.id===c.businessId);return `<button class="mini-list-item" data-route="inbox" data-conversation="${c.id}"><i class="list-icon">${c.channel.slice(0,1)}</i><div><b>${b?.short} — ${c.contact}</b><small>${c.preview}</small></div><span>${c.time}</span></button>`}).join("")}</div></article><article class="card"><header class="card-head"><div><h2>ملخص مسار المبيعات</h2><p>قيمة الصفقات بحسب المرحلة</p></div><button class="button ghost" data-route="pipeline">فتح مسار المبيعات</button></header><div class="funnel">${[["جديد",5,29],["تم التواصل",9,48],["مؤهل",12,67],["اجتماع",7,39],["عرض",8,45],["تفاوض",5,24]].map(([n,v,w])=>`<div class="funnel-row"><span>${n}</span><div class="funnel-bar"><i style="width:${w}%"></i></div><b>${v}</b></div>`).join("")}</div></article></section>`;
}
