// S2-FIX Design reminder: Arabic RTL executive dashboard; revenue and task widgets render from the linked mock model rather than duplicate view-model truth.
import { businesses, dashboardData, getAutomationMetrics, getDashboardMetrics, getInboxConversations, getPipelineStageSummary, getRevenueAttribution, getRevenueSummary, getUpcomingActivities, jobs, state } from "./data.js";
import { getAgentActions } from "./sales-ai.js";
import { getAnalyticsOverview, getAttributionTraces, getSourcePerformance } from "./analytics-engine.js";

export function renderDashboard(ctx) {
  const { fmt, button } = ctx;
  const money = (value) => `${fmt(value)} ر.س`;
  const data = dashboardData;
  const dashboardDateRange={"اليوم":"today","7 أيام":"last7","30 يومًا":"last30","هذا الربع":"all"}[state.dashboardTimeframe]||"all";
  const analytics = getAnalyticsOverview({ ...state.analyticsContext, dateRange:dashboardDateRange });
  const analyticsFunnel = analytics.funnel.stages;
  const analyticsSources = getSourcePerformance();
  const business = (id) => businesses.find((item) => item.id === id);
  const maxFunnel = analyticsFunnel[0]?.count || 1;
  const dashboardMetrics = [
    {label:"شركات مكتشفة",value:analytics.metrics.businessesDiscovered.value,format:"number",tone:"cyan",trend:"DiscoveryJob.completedAt",note:"ضمن فترة Dashboard"},
    {label:"عملاء محتملون",value:analytics.metrics.leadsCreated.value,format:"number",tone:"blue",trend:"Lead.createdAt",note:"حدث ضمن الفترة"},
    {label:"Pipeline المفتوحة",value:analytics.metrics.openPipeline.value,format:"sar",tone:"violet",trend:"لقطة حالية",note:"لا يطبق نطاق التاريخ"},
    {label:"الإيراد المعترف به",value:analytics.metrics.revenue.value,format:"sar",tone:"green",trend:"RevenueEvent.recognizedAt",note:"لا يستخدم قيمة Deal"},
    {label:"الإيراد المنسوب",value:analytics.metrics.attributedRevenue.value,format:"sar",tone:"cyan",trend:"multi-touch weighted",note:"من Touchpoints صالحة"},
    {label:"فرص عالية",value:analytics.metrics.highOpportunityBusinesses.value,format:"number",tone:"amber",trend:"OpportunityAnalysis.analyzedAt",note:"Score لا يساوي احتمال Deal"}
  ];
  const upcomingActivities = getUpcomingActivities();
  const revenueSummary = { revenue:analytics.metrics.revenue.value, pipeline:analytics.metrics.openPipeline.value, weightedPipeline:analytics.metrics.weightedPipeline.value, averageDeal:analytics.sales.averageDealValue, winRate:analytics.sales.winRate, averageCycle:"—" };
  const attributionSummary = getAttributionTraces(analytics.context).map(trace=>{const touch=trace.touchpoints[0];return {label:trace.event.id,sourceName:touch?.source?.name||"غير مكتمل",jobId:touch?.job?.id||"—",discovered:"—",qualified:"—",won:trace.deal?.status==="won"?1:0,revenueEventIds:[trace.event.id],revenue:trace.attributed};});
  const pipelineSummary = getPipelineStageSummary().filter(({ stage }) => stage.kind === "open");
  const maxPipelineStageValue = Math.max(...pipelineSummary.map((item) => item.value), 1);
  const recentConversations = getInboxConversations({ search:"", filter:"all", ownerId:"all", channel:"whatsapp", sort:"latest" }).slice(0,4);
  const agentActions = getAgentActions().slice(0,4);
  const automationMetrics = getAutomationMetrics();
  const timeframeTitles = { "اليوم":"ملخص أداء المبيعات واكتشاف العملاء اليوم", "7 أيام":"ملخص أداء المبيعات واكتشاف العملاء خلال آخر 7 أيام", "30 يومًا":"ملخص أداء المبيعات واكتشاف العملاء خلال آخر 30 يومًا", "هذا الربع":"ملخص أداء المبيعات واكتشاف العملاء خلال هذا الربع" };
  const timeframeTitle = timeframeTitles[state.dashboardTimeframe];

  const stateSwitcher = `<section class="dashboard-state-panel" aria-label="حالات عرض لوحة التحكم"><span>حالات اختبار الواجهة:</span><div>${[["ready","مكتمل"],["loading","تحميل"],["empty","فارغ"],["error","خطأ"]].map(([id,label])=>`<button type="button" class="${state.dashboardView===id?"active":""}" data-dashboard-view="${id}">${label}</button>`).join("")}</div></section>`;
  if (state.dashboardView !== "ready") {
    const configurations = {
      loading: ["تحميل", "يتم تجهيز ملخص الأداء التجريبي…", "↻", "loading"],
      empty: ["لا توجد بيانات كافية بعد", "ابدأ أول عملية اكتشاف لبناء لوحة الأداء ومسار المتابعة.", "○", "empty"],
      error: ["تعذر عرض الملخص التجريبي", "هذه حالة واجهة مخصصة للفحص فقط، ويمكن العودة إلى البيانات التجريبية.", "!", "error"]
    };
    const [title, description, icon, kind] = configurations[state.dashboardView];
    return `<div class="exec-dashboard">${stateSwitcher}<section class="dashboard-feedback ${kind}"><i>${icon}</i><h2>${title}</h2><p>${description}</p>${state.dashboardView === "empty" ? button("اكتشاف عملاء", "route-discovery", "button primary") : button("العودة إلى الملخص", "dashboard-ready", "button primary")}</section></div>`;
  }

  return `<div class="exec-dashboard">
    <section class="decision-rail" aria-label="مسار القرار"><div class="decision-brand"><img src="/manus-storage/leadflow-orbit-mark_f6c27956.png" alt="نمو"/>مسار القرار</div><div class="decision-steps"><span class="done"><i>١</i><b>اكتشاف</b></span><span class="done"><i>٢</i><b>فهم</b></span><span class="done"><i>٣</i><b>تواصل</b></span><span class="active"><i>٤</i><b>قرار</b></span><span><i>٥</i><b>إيراد</b></span></div><small>ملخص تنفيذي</small></section>
    <header class="exec-header"><div><p class="eyebrow">الرئيسية</p><h1>${timeframeTitle}</h1><p>هذه لوحة قيادة تجريبية تضع الفرص والقرارات ومصدر الإيراد في سياق واحد قابل للمراجعة.</p></div><div class="exec-header-actions"><div class="time-filter" aria-label="الفترة الزمنية">${["اليوم","7 أيام","30 يومًا","هذا الربع"].map(label=>`<button type="button" class="${state.dashboardTimeframe===label?"active":""}" data-dashboard-time="${label}">${label}</button>`).join("")}</div>${button("اكتشاف عملاء جدد", "route-discovery", "button primary")}<span class="exec-meta"><i></i>آخر تحديث تجريبي الآن</span></div></header>
    <div class="mock-strip"><b>بيانات تجريبية ثابتة</b><span>تطبق الفترة على event metrics؛ أما Pipeline واللقطات الحالية فتظهر كلقطات حالية صراحة.</span></div>
    ${stateSwitcher}
    <section class="exec-kpi-grid" aria-label="مؤشرات الأداء الرئيسية">${dashboardMetrics.map(metric=>`<article class="metric-card tone-${metric.tone}"><span>${metric.label}</span><b>${metric.format === "sar" ? money(metric.value) : fmt(metric.value)}</b><small class="metric-trend">${metric.trend}</small><div class="metric-foot"><i></i>${metric.note}</div></article>`).join("")}</section>
    <section class="executive-pair">
      <article class="card"><header class="card-head"><div><h2>يحتاج انتباهك</h2><p>عناصر محدودة تحتاج قرارًا أو متابعة من الفريق.</p></div></header><div class="attention-list">${data.attentionItems.map((item,index)=>`<article class="attention-item"><i class="attention-mark ${item.tone}">${String(index+1).padStart(2,"0")}</i><div><b>${item.title}</b><small>${item.description}</small></div><button type="button" class="button ghost" data-route="${item.route}">${item.action}</button></article>`).join("")}</div></article>
      <article class="card"><header class="card-head"><div><h2>توصيات الذكاء الاصطناعي</h2><p>توصيات قابلة للتنفيذ وليست نافذة محادثة.</p></div></header><div class="ai-recommendation-list">${data.aiRecommendations.map(recommendation=>{const related=business(recommendation.businessId);return `<article class="ai-recommendation"><header><span>${recommendation.kind}</span>${recommendation.score ? `<em class="score-inline">${recommendation.score}/100</em>` : ""}</header><b>${recommendation.title}</b><p>${recommendation.reason}</p><small>${recommendation.action}</small><footer><button type="button" class="button compact primary" data-route="${recommendation.primaryRoute}" ${related?`data-business="${related.id}"`:""}>${recommendation.primary}</button>${recommendation.secondary ? `<button type="button" class="button compact" data-action="${recommendation.secondaryAction}" data-business="${recommendation.businessId}">${recommendation.secondary}</button>` : ""}</footer></article>`;}).join("")}</div></article>
    </section>
    <section class="card"><header class="card-head"><div><h2>من الاكتشاف إلى الإيراد</h2><p>قمع مشتق من مجموعات Business فريدة؛ النسبة تقارن المرحلة بالمرحلة السابقة فقط.</p></div><button type="button" class="button ghost" data-route="analytics/funnel">عرض التحليل</button></header><div class="funnel-exec">${analyticsFunnel.map((stage,index)=>`<article class="funnel-stage-exec"><span>${stage.label}</span><b>${fmt(stage.count)}</b>${index ? `<small>${stage.conversion===null?"— · لا يوجد مقام سابق":`${stage.conversion}% انتقال من ${fmt(stage.denominator)}`}</small>` : `<small>نقطة بداية القمع</small>`}<i style="width:${Math.max(14,Math.round(stage.count/maxFunnel*100))}%"></i></article>`).join("")}</div></section>
    <section class="executive-pair">
      <article class="card"><header class="card-head"><div><h2>ملخص Pipeline</h2><p>قيمة الصفقات المفتوحة مشتقة من Deals ومراحلها الفعلية داخل S6.</p></div><button type="button" class="button ghost" data-route="pipeline">فتح المسار</button></header><div class="pipeline-summary">${pipelineSummary.map(({stage,count,value})=>`<button type="button" data-route="pipeline"><span>${stage.name}</span><b>${fmt(count)} صفقة</b><small>${money(value)}</small><i style="--share:${Math.min(100, Math.max(8, Math.round(value / maxPipelineStageValue * 100)))}%"></i></button>`).join("")}</div></article>
      <article class="card"><header class="card-head"><div><h2>أفضل مصادر العملاء</h2><p>تحويل Lead مشتق من Business وLead المتصلة بالمصدر عبر Job IDs.</p></div><button type="button" class="button ghost" data-route="analytics/sources">تفاصيل المصدر</button></header><div class="source-performance">${analyticsSources.map(source=>`<div class="source-bar info"><div><span>${source.sourceName}</span><i style="--source:${Math.max(0,source.leadConversion||0)}%"><b></b></i></div><strong>${source.leadConversion===null?"—":`${source.leadConversion}%`}</strong></div>`).join("")}</div></article>
    </section>
    <section class="executive-pair">
      <article class="card"><header class="card-head"><div><h2>صفقات قريبة من الإغلاق</h2><p>ثلاث صفقات تحتاج خطوة واضحة لتقليل وقت الإغلاق.</p></div><button type="button" class="button ghost" data-route="deals">كل الصفقات</button></header><div class="table-wrap"><table class="data-table deal-focus-table"><thead><tr><th>الصفقة</th><th>المرحلة</th><th>القيمة</th><th>الاحتمال</th><th>آخر نشاط</th><th>الإجراء التالي</th></tr></thead><tbody>${data.nearClosingDeals.map(deal=>{const item=business(deal.businessId);return `<tr><td><button type="button" data-route="lead-profile" data-business="${deal.businessId}">${item?.short || item?.name || deal.id}<small class="mono">${deal.id}</small></button></td><td><span class="status contact">${deal.stage}</span></td><td>${money(deal.value)}</td><td><b class="probability">${deal.probability}%</b></td><td>${deal.lastActivity}</td><td><small>${deal.nextAction}</small></td></tr>`;}).join("")}</tbody></table></div></article>
      <article class="card"><header class="card-head"><div><h2>أداء الاكتشاف</h2><p>تنتقل نتائج البحث التجريبية إلى مؤشرات تأهيل وCRM واضحة.</p></div><button type="button" class="button ghost" data-route="discovery">اكتشاف جديد</button></header><div class="table-wrap"><table class="data-table"><thead><tr><th>العملية</th><th>المصدر</th><th>الموقع</th><th>مكتشف</th><th>درجة عالية</th><th>أضيف إلى CRM</th><th>مؤهل</th><th>الحالة</th></tr></thead><tbody>${jobs.slice(0,3).map(job=>`<tr><td class="mono">${job.id}<small>${job.keyword}</small></td><td>${job.source}</td><td>${job.location}</td><td>${fmt(job.current)}</td><td>${fmt(job.highScore)}</td><td>${fmt(job.crmAdded)}</td><td>${fmt(job.qualified)}</td><td><span class="status ${job.status === "completed" ? "qualified" : "contact"}">${job.status === "completed" ? "مكتمل" : "قيد المعالجة"}</span></td></tr>`).join("")}</tbody></table></div></article>
    </section>
    <section class="executive-pair">
      <article class="card"><header class="card-head"><div><h2>المتابعات القادمة</h2><p>قائمة مشتقة من سجل المهام المركزي وربط العميل الفعلي.</p></div><button type="button" class="button ghost" data-route="tasks">كل المهام</button></header><div class="mini-list">${upcomingActivities.map(activity=>{const item=business(activity.businessId);const className=activity.status === "متأخر" ? "overdue" : activity.status === "اليوم" ? "today" : "upcoming";return `<button type="button" class="mini-list-item" data-route="${activity.route}" data-business="${activity.businessId}"><i class="list-icon">${activity.type.slice(0,1)}</i><div><b>${activity.title}</b><small>${item?.short || item?.name || "عميل تجريبي"} · ${activity.type}</small></div><span><em class="activity-status ${className}">${activity.status}</em><small>${activity.when}</small></span></button>`;}).join("")}</div></article>
      <article class="card"><header class="card-head"><div><h2>آخر المحادثات</h2><p>السياق التجاري والقناة والحالة بجانب آخر رسالة؛ واتساب في وضع تجريبي محلي.</p></div><button type="button" class="button ghost" data-route="inbox">فتح صندوق الوارد</button></header><div class="mini-list">${recentConversations.map(({conversation,business:relatedBusiness,contact,latest,needsReply})=>{const className=needsReply ? "today" : conversation.status === "closed" ? "upcoming" : "today";return `<button type="button" class="mini-list-item" data-route="inbox/${conversation.id}"><i class="list-icon">و</i><div><b>${relatedBusiness?.short || relatedBusiness?.name || contact?.name || "جهة اتصال"}</b><small>واتساب · ${latest?.body || "مرفق تجريبي"}</small></div><span><em class="activity-status ${className}">${needsReply ? "تحتاج ردًا" : conversation.status === "closed" ? "مغلقة" : "مفتوحة"}</em><small>${new Intl.DateTimeFormat("ar-SA",{hour:"2-digit",minute:"2-digit"}).format(new Date(conversation.lastMessageAt))}</small></span></button>`;}).join("")}</div></article>
    </section>
    <section class="card s8-dashboard-agent"><header class="card-head"><div><h2>مساعد المبيعات وAgent</h2><p>سجل اقتراحات محلية محكومة بالموافقة؛ لا يوجد تنفيذ ذاتي أو اتصال خارجي.</p></div><button type="button" class="button ghost" data-route="agent">فتح Agent</button></header><div class="mini-list">${agentActions.length ? agentActions.map(action=>`<button type="button" class="mini-list-item" data-route="agent"><i class="list-icon">✧</i><div><b>${action.type === "create_task" ? "إنشاء مهمة" : action.type === "update_lead_status" ? "تحديث حالة العميل" : action.type === "escalate_to_human" ? "تصعيد بشري" : action.type}</b><small>${action.status === "proposed" ? "بانتظار الموافقة البشرية" : action.status === "executed" ? "نُفذ بسجل تدقيق" : action.status === "failed" ? "فشل تجريبي واضح" : action.status}</small></div><span><em class="activity-status ${action.status === "proposed" ? "today" : action.status === "failed" ? "overdue" : "upcoming"}">ثقة ${Math.round(action.confidence * 100)}%</em><small>${action.id}</small></span></button>`).join("") : `<div class="crm-empty-inline">لا توجد اقتراحات Agent بعد.</div>`}</div></section>
    <section class="card s9-dashboard-automation"><header class="card-head"><div><h2>الأتمتة والمتابعات</h2><p>قواعد محلية حتمية تنشئ مهامًا أو اقتراحات بعد تقييم يدوي؛ لا يوجد Scheduler أو إرسال خارجي.</p></div><button type="button" class="button ghost" data-route="automation">فتح الأتمتة</button></header><div class="revenue-summary"><div><span>قواعد مفعلة</span><b>${fmt(automationMetrics.enabled)}</b></div><div><span>تشغيلات اليوم</span><b>${fmt(automationMetrics.runsToday)}</b></div><div><span>بانتظار موافقة</span><b>${fmt(automationMetrics.awaitingApproval)}</b></div><div><span>فشل مضبوط</span><b>${fmt(automationMetrics.failed)}</b></div></div></section>
    <section class="card"><header class="card-head"><div><h2>ملخص الإيراد</h2><p>الإيراد المعترف به يأتي من RevenueEvents، بينما قيمة Pipeline المفتوحة تأتي من Deals الحالية ولا تختلط به.</p></div><button type="button" class="button ghost" data-route="analytics">تحليل الإيراد</button></header><div class="revenue-summary"><div><span>إيراد العرض التجريبي</span><b>${money(revenueSummary.revenue)}</b></div><div><span>قيمة Pipeline المفتوحة</span><b>${money(revenueSummary.pipeline)}</b></div><div><span>Pipeline المرجحة</span><b>${money(revenueSummary.weightedPipeline)}</b></div><div><span>متوسط الصفقة الرابحة</span><b>${money(revenueSummary.averageDeal)}</b></div><div><span>معدل الفوز</span><b>${revenueSummary.winRate}%</b></div><div><span>متوسط دورة البيع</span><b>${revenueSummary.averageCycle}</b></div></div></section>
    <section class="card"><header class="card-head"><div><h2>من أين جاء الإيراد؟</h2><p>مشتق من أحداث إيراد معترف بها مرتبطة بصفقة وعميل وعملية اكتشاف ومصدر فعلي. إجمالي الإسناد يطابق إيراد العرض التجريبي.</p></div><button type="button" class="button ghost" data-route="analytics">عرض الإسناد</button></header><div class="attribution-snapshot">${attributionSummary.map(source=>`<article class="attribution-source"><h3>${source.label}</h3><dl><div><dt>مصدر الاكتشاف</dt><dd>${source.sourceName}</dd></div><div><dt>عملية البحث</dt><dd>${source.jobId}</dd></div><div><dt>مكتشف</dt><dd>${fmt(source.discovered)}</dd></div><div><dt>مؤهل</dt><dd>${fmt(source.qualified)}</dd></div><div><dt>رابح</dt><dd>${fmt(source.won)}</dd></div><div><dt>حدث الإيراد</dt><dd>${source.revenueEventIds.join("، ")}</dd></div></dl><footer><span>الإيراد المنسوب</span><b>${money(source.revenue)}</b></footer></article>`).join("")}</div></section>
  </div>`;
}
