/* S12 / V1-FINAL-FIX: Landing reads shared S10 selectors and BUS-1042 intelligence; no duplicated financial fixtures. */
import { mockModel } from "./data.js";
import { getAnalyticsOverview } from "./analytics-engine.js";
import { getBusinessIntelligence } from "./intelligence.js";

const arabicNumber = (value) => new Intl.NumberFormat("ar-SA").format(Number(value || 0));
const sar = (value) => `${arabicNumber(value)} ر.س`;
const escapeHtml = (value) => String(value ?? "").replace(/[&<>"]/g, (char) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;" })[char]);

export function getLandingTruth(context = { dateRange:"all" }) {
  const overview = getAnalyticsOverview(context);
  const intelligence = getBusinessIntelligence("BUS-1042");
  const funnel = new Map(overview.funnel.stages.map((stage) => [stage.id, stage]));
  const metrics = overview.metrics;
  const business = intelligence?.business || {};
  const reasons = (intelligence?.reasons || []).filter((reason) => reason.polarity === "gap").map((reason) => reason.text).slice(0, 3);
  const services = (intelligence?.services || []).map((service) => service.name).slice(0, 3);
  return { overview, intelligence, funnel, metrics, business, reasons, services };
}

export function renderLandingTruth({ brand, button }) {
  const { overview, intelligence, funnel, metrics, business, reasons, services } = getLandingTruth();
  const stage = (id) => funnel.get(id) || { count:0, label:id };
  const heroStages = [
    ["discovered", "شركة مكتشفة", "اكتشاف"], ["high", "فرصة عالية", "تحليل"], ["lead", "عميل محتمل", "تأهيل"], ["deal", "صفقة", "مبيعات"], ["won", "صفقة رابحة", "إيراد"]
  ];
  const attributionStages = ["discovered", "high", "lead", "deal", "won"].map((id) => stage(id));
  const period = "كل الفترة التجريبية";
  const businessName = escapeHtml(business.name || "شركة تجريبية");
  const businessId = escapeHtml(business.id || "");
  const city = escapeHtml(business.city || "");
  const score = intelligence?.score ?? 0;
  const confidence = Math.round((intelligence?.confidence || 0) * 100);
  const serviceLabels = services.length ? services : ["خدمة مرتبطة بالفجوة المثبتة"];
  const reasonLabels = reasons.length ? reasons : ["تُعرض الأدلة عند اكتمال التحليل"];
  const pipelineCards = [
    ["الصفقات المفتوحة", metrics.openDeals.value, "من مصدر الصفقات الحالي"],
    ["قيمة مسار المبيعات", sar(metrics.openPipeline.value), "لقطة حالية — لا يطبق عليها نطاق التاريخ"],
    ["مسار المبيعات المرجّح", sar(metrics.weightedPipeline.value), "القيمة × احتمال الصفقة"]
  ];
  const integrations = [["خرائط الأعمال","محاكاة محلية"],["واتساب","محاكاة محلية"],["إنستغرام","قريبًا"],["دردشة الموقع","مخطط"],["التقويم","قريبًا"],["نظام إدارة العملاء","استيراد تجريبي"],["الخطافات البرمجية","معطّل تجريبيًا"],["واجهة برمجية","مخطط"]];
  const workflow = [["01","اكتشف","حدد القطاع والموقع والمعايير."],["02","افهم","حلّل الحضور الرقمي والإشارات وفرص البيع."],["03","رتّب","احصل على درجة فرصة وأولوية واضحة."],["04","تواصل","انقل العميل إلى إدارة العملاء وابدأ المتابعة."],["05","حوّل","تابع الصفقة واعرف أي مصدر أنتج الإيراد."]];
  return `<div class="public-shell landing-shell">
    <nav class="public-nav landing-nav" aria-label="التنقل العام">${brand()}<div class="public-nav-links"><a href="#platform">المنصة</a><a href="#workflow">كيف تعمل</a><a href="#intelligence">الذكاء الاصطناعي</a><a href="#uses">الاستخدامات</a><a href="#/login">الدخول</a></div><div class="public-actions">${button("ابدأ الآن", "go-onboarding", "button primary")}</div></nav>
    <main>
      <section class="hero landing-hero" id="platform"><div class="hero-copy"><p class="eyebrow">منصة ذكاء المبيعات واكتساب العملاء</p><h1>من اكتشاف العميل إلى إغلاق الصفقة — في منصة واحدة</h1><p class="lead">اكتشف الشركات المناسبة، حلّل فرص البيع لديها، رتّب أولويات فريقك، تواصل مع العملاء، وتابع رحلة البيع كاملة حتى الإيراد.</p><div class="hero-actions">${button("ابدأ تجربة المنصة", "go-onboarding", "button primary")}${button("شاهد كيف تعمل", "scroll-workflow", "button")}</div><p class="hero-note"><i></i>نموذج تفاعلي ببيانات تجريبية؛ لا توجد عمليات بحث أو رسائل أو تكاملات حقيقية.</p></div><div class="hero-visual source-revenue-visual"><div class="source-revenue-head"><span>حقيقة تجريبية مشتركة</span><b>${period}</b></div><div class="source-query"><span>قمع الاكتساب</span><b>مشتق من محرك التحليلات</b><small>لا يعاد احتسابه داخل Landing</small></div><div class="source-flow">${heroStages.map(([id,label,stageLabel],index)=>`<div class="source-flow-row ${id==="won"?"revenue-row":""}"><i>${index+1}</i><div><span>${stageLabel}</span><b>${label}</b></div><strong>${arabicNumber(stage(id).count)}</strong></div>`).join("")}</div><div class="source-revenue-footer"><span>الإيراد المنسوب</span><b>${sar(metrics.attributedRevenue.value)}</b><small>${period} · مشتق من نقاط إسناد S10 الصالحة</small></div></div></section>
      <section class="workflow-strip" id="workflow"><div class="landing-section-title"><p class="eyebrow">سير العمل</p><h2>كيف تعمل المنصة؟</h2><p>لا تبدأ من قائمة أسماء؛ بل من إشارة يمكن تتبعها حتى نتيجة بيع واضحة.</p></div><div class="workflow-steps product-workflow">${workflow.map(([n,a,b])=>`<article class="workflow-step"><span>${n}</span><b>${a}</b><small>${b}</small></article>`).join("")}</div></section>
      <section class="landing-section discovery-section"><div class="section-head"><div><p class="eyebrow">اكتشاف مدعوم بالبيانات</p><h2>لا تبحث عن أسماء فقط — ابحث عن فرص بيع</h2></div><p>كل شركة تظهر كسجل قابل للفهم، وليس كسطر معزول في ملف.</p></div><div class="discovery-showcase"><article class="business-preview"><header><div><span class="eyebrow">سجل شركة من الحقيقة التشغيلية</span><h3>${businessName}</h3><small class="mono">${businessId}${city ? ` · ${city}` : ""}</small></div><span class="score high">${arabicNumber(score)}</span></header><div class="business-facts"><span><small>التقييم</small><b>${arabicNumber(business.rating)}</b></span><span><small>المراجعات</small><b>${arabicNumber(business.reviews)}</b></span><span><small>التحليل</small><b class="text-green">${escapeHtml(intelligence?.status === "analyzed" ? "مكتمل" : "قيد المراجعة")}</b></span><span><small>الثقة</small><b>${arabicNumber(confidence)}%</b></span><span><small>درجة الفرصة</small><b>${arabicNumber(score)} / ١٠٠</b></span></div><footer><span>خدمات مرتبطة بأدلة</span><div>${serviceLabels.map((service)=>`<em>${escapeHtml(service)}</em>`).join("")}</div></footer></article><aside class="discovery-copy"><p class="eyebrow">من مصدر أعمال إلى سياق بيع</p><h3>تبدأ الرحلة بالمصدر، لكنها لا تنتهي عنده.</h3><p>يُحفظ الأصل، ثم تُضاف إشارات النشاط والفجوات الرقمية والتوصية الخدمية بجانب الشركة لتوجيه الفريق إلى الخطوة التالية.</p>${button("اكتشف كيف يتم تحليل الفرص", "show-landing-demo", "button")}</aside></div></section>
      <section class="landing-section intelligence-section" id="intelligence"><div class="section-head"><div><p class="eyebrow">ذكاء فرص العملاء</p><h2>كل عميل يأتي مع سبب واضح لكونه فرصة</h2></div><p>الذكاء الاصطناعي هنا طبقة تحليل وقرار، وليس نافذة محادثة منفصلة.</p></div><div class="intelligence-showcase"><article class="intelligence-reason"><header><span>لماذا هذا العميل مهم؟</span><b>إشارات قابلة للمراجعة</b></header><p>تستند التوصية إلى الإشارات والفجوات المثبتة في ملف الشركة الحالي.</p><div class="signal-list">${reasonLabels.map((reason)=>`<span><i>!</i>${escapeHtml(reason)}</span>`).join("")}</div><footer><small>الخدمات المقترحة</small><b>${serviceLabels.map(escapeHtml).join(" + ")}</b></footer></article><article class="intelligence-meta"><span>درجة الفرصة</span><b class="mono">${arabicNumber(score)}/100</b><small>ثقة ${arabicNumber(confidence)}% · مراجعة بشرية مطلوبة</small><div><em>الفجوات المثبتة</em><em>أسلوب البيع المقترح</em><em>الإجراء التالي</em></div></article></div></section>
      <section class="landing-section context-section"><div class="section-head"><div><p class="eyebrow">سياق متصل</p><h2>لا تفقد سياق العميل بعد الاكتشاف</h2></div><p>تتحرك نفس الهوية من الشركة إلى العميل المحتمل والمحادثة والصفقة، بينما يظل الإيراد ملخصًا مستقلًا للفترة.</p></div><div class="record-chain"><article><span class="mono">${businessId}</span><b>شركة</b><small>البيانات والإشارات</small></article><i>↓</i><article><span class="mono">LEAD-1042</span><b>عميل محتمل</b><small>المالك ودرجة الفرصة</small></article><i>↓</i><article><span class="mono">CONV-3042</span><b>محادثة</b><small>السياق والمتابعة</small></article><i>↓</i><article><span class="mono">DEAL-4042</span><b>صفقة</b><small>قيمة واحتمال مستقلان</small></article><i>↓</i><article class="revenue"><span>${sar(metrics.revenue.value)}</span><b>إيراد معترف به</b><small>${period} · ملخص S10 وليس قيمة صفقة واحدة</small></article></div></section>
      <section class="landing-section copilot-section"><div class="copilot-landing"><div><p class="eyebrow">مساعد المبيعات الذكي</p><h2>الذكاء الاصطناعي يساعد فريق المبيعات على اتخاذ الخطوة التالية</h2><p>يربط الإشارة والوقت والسياق ليقترح الإجراء التالي، بينما تبقى المراجعة البشرية جزءًا أساسيًا من القرار.</p></div><article><span>تنبيه متابعة</span><h3>راجع السياق قبل اتخاذ الخطوة التالية.</h3><dl><div><dt>الفرصة</dt><dd>تُراجع بشريًا</dd></div><div><dt>أفضل إجراء الآن</dt><dd>صياغة مسودة ومراجعتها</dd></div><div><dt>الإرسال</dt><dd>بشري ومحلي فقط</dd></div></dl><div class="copilot-actions">${["صياغة متابعة","إنشاء مهمة","تلخيص العميل","اقتراح الخطوة التالية"].map(label=>button(label,"show-landing-demo","button")).join("")}</div></article></div></section>
      <section class="landing-section pipeline-section"><div class="section-head"><div><p class="eyebrow">متابعة المبيعات</p><h2>ملخص مسار المبيعات الحالي</h2></div><p>لقطة مشتقة من الصفقات الحالية؛ لا تمثل إيرادًا خلال الفترة.</p></div><div class="landing-kanban">${pipelineCards.map(([label,value,description])=>`<article><header><b>${label}</b></header><div><span>س</span><b>${value}</b><small>${description}</small></div></article>`).join("")}</div></section>
      <section class="landing-section attribution-section"><div class="attribution-landing"><header><p class="eyebrow">نسبة الإيراد</p><h2>اعرف أي مراحل اكتساب تؤدي إلى إيراد</h2><p>القمع والإيراد يعتمدان محرك S10 نفسه وبنفس دلالة الفترة.</p></header><div class="attribution-landing-flow">${attributionStages.map((item)=>`<article><span>${item.label}</span><b>${arabicNumber(item.count)}</b></article><i>↓</i>`).join("")}<article class="revenue"><span>الإيراد المعترف به</span><b>${sar(metrics.revenue.value)}</b><small>${period}</small></article></div></div></section>
      <section class="landing-section uses-section" id="uses"><div class="section-head"><div><p class="eyebrow">لمن صُممت</p><h2>للفرق التي تريد تحويل الإشارات إلى قرارات بيع</h2></div><p>تركيز واضح على حالات الاستخدام التي تحتاج اكتسابًا منظمًا ومتابعة قابلة للقياس.</p></div><div class="uses-grid">${["وكالات التسويق","فرق مبيعات الشركات","شركات الخدمات","العقار","العيادات","شركات التقنية","فرق توليد العملاء"].map((use,index)=>`<article><i>${String(index+1).padStart(2,"0")}</i><b>${use}</b><span>اكتشاف، فهم، متابعة، وقياس.</span></article>`).join("")}</div></section>
      <section class="landing-section integrations-preview"><div class="section-head"><div><p class="eyebrow">طبقة تكامل</p><h2>مصادر وقنوات ووجهات ضمن مسار واحد</h2></div><p>المعروض أدناه حالة تخطيطية داخل Prototype ولا يمثل تكاملات تشغيلية حقيقية.</p></div><div class="integration-preview-grid">${integrations.map(([name,status],index)=>`<article><i>${String(index+1).padStart(2,"0")}</i><div><b>${name}</b><small class="${status.includes("محاكاة")?"planned":status==="قريبًا"?"soon":"available"}">${status}</small></div></article>`).join("")}</div></section>
      <section class="final-cta"><div><p class="eyebrow">ابدأ من مسار واضح</p><h2>حوّل اكتشاف العملاء إلى عملية مبيعات قابلة للقياس</h2><p>ابدأ بإعداد مساحة العمل، ثم اتبع رحلة تجريبية تشرح كيف تتصل البيانات والفرص والمبيعات.</p></div><div>${button("ابدأ الآن","go-onboarding","button primary")}${button("استكشف المنصة","go-login","button")}</div></section>
    </main>
    <footer class="landing-footer"><div>${brand()}<p>نموذج تجريبي لعرض تجربة منتج اكتساب العملاء والمبيعات.</p></div><div><b>المنتج</b><a href="#platform">المنصة</a><a href="#workflow">الاكتشاف</a><a href="#workflow">إدارة العملاء</a><a href="#intelligence">الذكاء الاصطناعي</a><a href="#workflow">التحليلات</a></div><div><b>الشركة</b><a href="#platform">عن المنصة</a><a href="#/login">التواصل</a><a href="#/login">الخصوصية</a><a href="#/login">الشروط</a></div><div><b>تقني</b><a href="#/login">واجهة برمجية</a><a href="#/login">تكاملات</a><a href="#/login">التوثيق</a></div></footer>
  </div>`;
}
