// Design reminder: Supporting operations still reveal the linked product model: work is connected to a lead, a source, an owner, and a commercial outcome.
import { activities, businesses, metrics } from "./data.js";

const stageArabic = {New:"جديد",Contacted:"تم التواصل",Qualified:"مؤهل",Meeting:"اجتماع",Proposal:"عرض",Negotiation:"تفاوض",Won:"رابحة",Lost:"خاسرة"};

export function renderTasks(ctx) {
  const { button, pageHead } = ctx;
  const today = activities.filter((_,i)=>i<2), upcoming = activities.filter((_,i)=>i>=2);
  const task = (a, overdue=false) => { const b=businesses.find(x=>x.id===a.businessId); return `<article class="task-card"><span class="task-type ${a.type.toLowerCase()}">${a.type}</span><div><b>${a.title}</b><small>${b?.name} · ${a.when}</small></div><button data-route="lead-profile" data-business="${a.businessId}">فتح العميل</button>${overdue?`<em>متأخر</em>`:""}</article>`; };
  return `${pageHead("Tasks & Appointments", "مهام المتابعة والمواعيد", "تظهر المهمة بجوار العميل ومرحلة البيع وسياق الفرصة، وليس كتذكير منفصل بلا علاقة.", button("إنشاء مهمة", "create-task", "button primary"))}<section class="task-summary"><article><span>مهام اليوم</span><b>12</b><small class="text-cyan">4 عالية الأولوية</small></article><article><span>مواعيد قادمة</span><b>5</b><small class="text-green">2 مع فرص عالية</small></article><article><span>متابعة متأخرة</span><b>3</b><small class="text-red">تحتاج تدخلًا اليوم</small></article><article><span>مقترحات Copilot</span><b>8</b><small>نشاطات موصى بها</small></article></section><section class="grid grid-2" style="margin-top:16px"><article class="card"><header class="card-head"><div><h2>اليوم</h2><p>إجراءات جاهزة للفريق</p></div><span class="pill"><i></i>12 مهمة</span></header><div class="task-list">${today.map(a=>task(a)).join("")}${task({type:"Follow-up",title:"مراجعة عرض مركز ابتسامة",when:"16:30",businessId:"BUS-1137"})}</div></article><article class="card"><header class="card-head"><div><h2>قادم</h2><p>مواعيد وأنشطة خلال الأيام التالية</p></div><button class="button ghost" data-action="open-calendar">فتح التقويم</button></header><div class="task-list">${upcoming.map(a=>task(a)).join("")}${task({type:"Proposal",title:"إرسال عرض خدمات لعيادات الحياة",when:"الخميس، 12:00",businessId:"BUS-1042"})}</div></article></section><section class="card" style="margin-top:16px"><header class="card-head"><div><h2>متابعة تحتاج اهتمامًا</h2><p>هذه العناصر متأخرة أو بلا مالك واضح</p></div></header><div class="task-list">${task({type:"WhatsApp",title:"لم يرد مركز ابتسامة منذ 3 أيام",when:"متأخر 3 أيام",businessId:"BUS-1137"},true)}${task({type:"Call",title:"تأكيد متطلبات شركة المدار",when:"متأخر يوم",businessId:"BUS-1220"},true)}</div></section>`;
}

export function renderDeals(ctx) {
  const { button, pageHead, sar } = ctx; const b=businesses.find(x=>x.id==="BUS-1042")||businesses[0];
  return `${pageHead("Deals", "الصفقات وتوقعات الإغلاق", "كل صفقة مرتبطة بعميل ومصدر اكتشاف وأنشطة ومخاطر وخطوة تالية موصى بها.", button("إنشاء صفقة", "create-deal", "button primary"))}<section class="deal-detail"><article class="deal-main"><span class="pill success"><i></i>Likely to close</span><h2>Website + Marketing Automation</h2><p>${b.name} · ${b.category} · مصدرها <button data-route="results" class="link-like">DISC-1028</button></p><div class="deal-kpis"><span><small>قيمة الصفقة</small><b>${sar(85000)}</b></span><span><small>الاحتمالية</small><b>74%</b></span><span><small>تاريخ الإغلاق</small><b>30 يونيو</b></span><span><small>المالك</small><b>${b.owner}</b></span></div><div class="deal-steps">${[["تم التأهيل","done"],["اجتماع","done"],["عرض","current"],["تفاوض",""],["رابحة",""]].map(([x,c])=>`<span class="${c}"><i>${c==="done"?"✓":x.slice(0,1)}</i>${x}</span>`).join("")}</div></article><aside class="deal-forecast"><p class="eyebrow">AI Forecast</p><h3>Likely to close</h3><p>الإشارات الإيجابية: اجتماع تم، اهتمام واضح بأتمتة الحجز، ووجود ميزانية أولية.</p><div><span>الخطر الرئيسي</span><b>التسعير</b></div><div><span>Next Best Action</span><b>Schedule technical demo</b></div>${button("حجز العرض التقني", "create-task", "button primary")}</aside></section><section class="grid grid-main-side" style="margin-top:16px"><article class="card"><header class="card-head"><div><h2>نشاطات الصفقة</h2><p>كل خطوة مرتبطة بسجل العميل نفسه</p></div></header><div class="deal-activity">${[["اليوم · 10:42","رد العميل في WhatsApp","مهتم بمراجعة التقنية قبل العرض النهائي","WhatsApp"],["أمس · 14:10","مكالمة استكشافية","تم تأكيد الحاجة إلى أتمتة متابعة الحجوزات","Call"],["12 يونيو","تم إنشاء العرض الأولي","قيمة مقترحة SAR 85,000","Proposal"],["10 يونيو","تمت إضافة العميل إلى CRM","من Job DISC-1028","Discovery"]].map(([when,title,desc,type])=>`<article><span>${type}</span><div><b>${title}</b><p>${desc}</p></div><small>${when}</small></article>`).join("")}</div></article><aside class="card pad"><p class="eyebrow">الارتباط</p><h3 style="margin:0;font-size:16px">Lead-to-Deal Attribution</h3><p class="muted" style="font-size:10px;line-height:1.8">ستظهر هذه الصفقة في Analytics كإيراد مرتبط ببحث عيادات الأسنان في الرياض.</p><div class="attribution-chain"><span>DISC-1028</span><i>↓</i><span>BUS-1042</span><i>↓</i><span>DEAL-2008</span></div></aside></section>`;
}

export function renderAnalytics(ctx) {
  const { button, pageHead, fmt, sar } = ctx;
  const bars=[["Google Maps",47],["Website",28],["Import",15],["Referral",10]], cities=[["الرياض",62],["جدة",24],["الدمام",14]];
  const attribution = [["Google Maps Search","Clinics Riyadh",""],["Discovered","1,240",""],["Added to CRM","380",""],["Contacted","250",""],["Qualified","84",""],["Deals","32",""],["Won","11","won"],["Revenue","SAR 428,000","revenue"]];
  return `${pageHead("Analytics", "من الاكتشاف إلى الإيراد", "ليست Analytics سطحية: نعرض أي Job وSource أديا فعليًا إلى CRM ومحادثة وصفقة وإيراد.", `${button("تصدير تقرير", "export-analytics", "button")}${button("فتح Attribution", "scroll-attribution", "button primary")}`)}<section class="stats-grid"><article class="metric-card"><span>Pipeline Value</span><b>${sar(metrics.pipelineValue)}</b><small>164 صفقة مفتوحة</small></article><article class="metric-card highlight"><span>Won Revenue</span><b>${sar(metrics.wonMonth)}</b><small>284 صفقة رابحة</small></article><article class="metric-card"><span>AI Qualified</span><b>37</b><small>ضمن هذا الأسبوع</small></article><article class="metric-card"><span>Human Handoff Rate</span><b>14%</b><small>ضمن المحادثات النشطة</small></article></section><section class="grid grid-2" style="margin-top:16px"><article class="card pad"><div class="chart-head"><div><p class="eyebrow">Acquisition Analytics</p><h3>Leads by Source</h3></div><span class="pill"><i></i>آخر 30 يومًا</span></div><div class="bar-chart">${bars.map(([n,v])=>`<div><span>${n}</span><i><b style="width:${v}%"></b></i><em>${v}%</em></div>`).join("")}</div></article><article class="card pad"><div class="chart-head"><div><p class="eyebrow">Market focus</p><h3>Leads by City</h3></div><span class="pill"><i></i>Saudi Arabia</span></div><div class="bar-chart">${cities.map(([n,v])=>`<div><span>${n}</span><i><b style="width:${v}%"></b></i><em>${v}%</em></div>`).join("")}</div></article></section><section class="grid grid-2" style="margin-top:16px"><article class="card pad"><div class="chart-head"><div><p class="eyebrow">Sales conversion</p><h3>Funnel conversion</h3></div></div><div class="conversion-chain">${[["Lead",12480],["Contact",2940],["Qualified",920],["Proposal",476],["Won",284]].map(([n,v],i)=>`<div><b>${fmt(v)}</b><span>${n}</span>${i<4?"<i>←</i>":""}</div>`).join("")}</div></article><article class="card pad"><div class="chart-head"><div><p class="eyebrow">AI Analytics</p><h3>AI influence</h3></div></div><div class="ai-metric-list">${[["AI Conversations",184],["AI Appointments",12],["AI Assisted Deals",26],["AI Influenced Revenue",sar(146000)]].map(([n,v])=>`<div><span>${n}</span><b>${v}</b></div>`).join("")}</div></article></section><section class="attribution-card" id="attribution"><div class="attribution-head"><div><p class="eyebrow">Core Product Metric</p><h2>Lead-to-Revenue Attribution</h2><p>أي عملية Discovery أدت فعلًا إلى Revenue؟</p></div><span class="pill success"><i></i>قصة مكتملة</span></div><div class="attribution-flow">${attribution.map(([a,b,c],i)=>`<button class="${c}" ${a==="Won"?"data-action=\"view-won-deals\"":""}><span>${String(i+1).padStart(2,"0")}</span><b>${a}</b><small>${b}</small></button>`).join("<i>←</i>")}</div><p class="attribution-note">بحث واحد بدأ بعيادات الأسنان في الرياض، ثم أنتج قائمة، ثم CRM، ثم محادثات وDeals، وانتهى بإيراد يمكن لفريق النمو تفسيره.</p></section>`;
}

export function renderIntegrations(ctx) {
  const { button, pageHead } = ctx; const cards=[["Google Maps","Lead Sources","Connected","MAP"],["WhatsApp","Communication","Connected","WA"],["Instagram","Communication","Not Connected","IG"],["Facebook","Communication","Coming Soon","FB"],["Website Chat","Communication","Connected","WC"],["Google Calendar","Calendar","Not Connected","GC"],["Salla","Commerce","Coming Soon","SA"],["Zid","Commerce","Coming Soon","ZI"],["Shopify","Commerce","Not Connected","SH"],["WooCommerce","Commerce","Not Connected","WO"],["Zapier","Automation","Coming Soon","ZA"],["Webhook","Automation","Connected","<>"],["REST API","Automation","Connected","API"]];
  return `${pageHead("Integrations", "Integrations Marketplace", "مصادر leads، قنوات تواصل، CRM، تقويم وأتمتة — كلها موصولة بمسار العميل الواحد.", button("إضافة Custom API", "add-integration", "button primary"))}<section class="integration-tabs">${["الكل","Lead Sources","Communication","CRM","Commerce","Automation","Calendar"].map((x,i)=>`<button class="${i===0?"active":""}">${x}</button>`).join("")}</section><section class="integration-grid">${cards.map(([name,type,status,mark])=>`<article><i>${mark}</i><div><span>${type}</span><h3>${name}</h3><p>${status==="Connected"?"متصل ويظهر في سياق العميل":"قابل للربط في مرحلة التكامل الحقيقية"}</p></div><footer><em class="${status==="Connected"?"connected":status==="Coming Soon"?"coming":""}">${status}</em>${button(status==="Connected"?"إدارة":"ربط تجريبي",status==="Connected"?"manage-integration":"connect-integration","button")}</footer></article>`).join("")}</section>`;
}

export function renderBilling(ctx) {
  const { button, pageHead, sar } = ctx;
  return `${pageHead("Billing", "الخطة والاستخدام", "هذه الشاشة توضيحية فقط: لا توجد مدفوعات أو اشتراكات حقيقية داخل الـPrototype.", button("تحديث الخطة", "upgrade-plan", "button primary"))}<section class="billing-hero"><div><span class="pill success"><i></i>Growth Plan</span><h2>خطة النمو</h2><p>لفريق اكتساب العملاء والمبيعات الذي يحتاج اكتشافًا وتحليلًا وCRM وAI Sales Agent في مساحة واحدة.</p></div><div><b>SAR 2,400</b><span>/ شهر</span><small>Mock billing only</small></div></section><section class="grid grid-3" style="margin-top:16px"><article class="card pad"><p class="eyebrow">Discovery credits</p><h3 style="margin:0;font:23px var(--mono)">1,240 <small class="muted">/ 2,000</small></h3><div class="usage-meter"><i style="width:62%"></i></div><p class="muted" style="font-size:10px">تُعاد في 12 يومًا</p></article><article class="card pad"><p class="eyebrow">AI analyses</p><h3 style="margin:0;font:23px var(--mono)">386 <small class="muted">/ 1,000</small></h3><div class="usage-meter"><i style="width:38%"></i></div><p class="muted" style="font-size:10px">ضمن الخطة الحالية</p></article><article class="card pad"><p class="eyebrow">Agent conversations</p><h3 style="margin:0;font:23px var(--mono)">184 <small class="muted">/ 500</small></h3><div class="usage-meter"><i style="width:37%"></i></div><p class="muted" style="font-size:10px">تحتاج ربط القنوات في المنتج الحقيقي</p></article></section><section class="card" style="margin-top:16px"><header class="card-head"><div><h2>الفواتير التجريبية</h2><p>عرض فقط — لا توجد عملية دفع</p></div></header><div class="table-wrap"><table class="data-table"><thead><tr><th>الفاتورة</th><th>التاريخ</th><th>الخطة</th><th>المبلغ</th><th>الحالة</th><th></th></tr></thead><tbody>${[["INV-2025-06","01 يونيو","Growth Plan",sar(2400),"Paid"],["INV-2025-05","01 مايو","Growth Plan",sar(2400),"Paid"],["INV-2025-04","01 أبريل","Growth Plan",sar(2400),"Paid"]].map(([a,b,c,d,e])=>`<tr><td class="mono">${a}</td><td>${b}</td><td>${c}</td><td>${d}</td><td><span class="status qualified">${e}</span></td><td>${button("عرض", "show-invoice", "button ghost")}</td></tr>`).join("")}</tbody></table></div></section>`;
}

export function renderSettings(ctx) {
  const { button, pageHead } = ctx;
  return `${pageHead("Settings", "إعدادات مساحة العمل", "إعدادات محلية لتوضيح بنية المنتج. الحفظ لا يغيّر بيانات خارج المتصفح.", button("حفظ التغييرات", "save-settings", "button primary"))}<section class="settings-layout"><aside class="settings-nav">${["عام","الفريق والصلاحيات","مصادر البيانات","قنوات التواصل","AI & Copilot","الإشعارات","الأمان"].map((x,i)=>`<button class="${i===0?"active":""}">${x}</button>`).join("")}</aside><div class="settings-content"><section class="card pad"><p class="eyebrow">General</p><h2 style="margin:0 0 18px;font-size:18px">إعدادات عامة</h2><div class="form-grid"><div class="form-field"><label>اسم مساحة العمل</label><input value="وكالة نمو الرقمية"/></div><div class="form-field"><label>المنطقة الزمنية</label><select><option>Asia/Riyadh (GMT+3)</option></select></div><div class="form-field"><label>اللغة الافتراضية</label><select><option>العربية (RTL)</option><option>English (LTR)</option></select></div><div class="form-field"><label>العملة</label><select><option>SAR — الريال السعودي</option></select></div></div></section><section class="card pad" style="margin-top:16px"><p class="eyebrow">Product defaults</p><h2 style="margin:0 0 13px;font-size:18px">سلوك الاكتشاف والـAI</h2><div class="setting-toggle"><div><b>التحليل التلقائي للفرص العالية</b><small>يضيف AI Opportunity Analysis بعد ظهور نتيجة بدرجة عالية.</small></div><label class="switch"><input type="checkbox" checked/><i></i></label></div><div class="setting-toggle"><div><b>طلب موافقة قبل إرسال الرسائل</b><small>يبقي قنوات التواصل تحت مراجعة بشرية.</small></div><label class="switch"><input type="checkbox" checked/><i></i></label></div><div class="setting-toggle"><div><b>إظهار Lead-to-Revenue Attribution</b><small>يعرض ارتباط المصدر بالصفقات والإيراد في Analytics.</small></div><label class="switch"><input type="checkbox" checked/><i></i></label></div></section></div></section>`;
}
