// Design reminder: Sales surfaces maintain the lead's discovery context. CRM, conversations, AI guidance, and pipeline are different views of the same shared entity.
import { businesses, conversations, state } from "./data.js";

const stages = ["New","Contacted","Qualified","Meeting","Proposal","Negotiation","Won","Lost"];
const stageArabic = {New:"جديد",Contacted:"تم التواصل",Qualified:"مؤهل",Meeting:"اجتماع",Proposal:"عرض",Negotiation:"تفاوض",Won:"رابحة",Lost:"خاسرة"};

export function renderCrm(ctx) {
  const { button, pageHead, sar, statusClass } = ctx;
  return `${pageHead("CRM Leads", "العملاء المحتملون داخل CRM", "المصدر ليس مجرد حقل؛ يمكن تتبع كل Lead حتى Job الاكتشاف والتحليل والمحادثة والصفقة.", `${button("استيراد", "crm-import", "button")}${button("إضافة Lead", "crm-add-lead", "button primary")}`)}<section class="card"><div class="toolbar"><div class="toolbar-right"><div class="search-field"><span>⌕</span><input placeholder="ابحث في العملاء المحتملين"/></div><button class="filter-chip active">كل المصادر</button><button class="filter-chip">Score +80</button><button class="filter-chip">متابعة اليوم</button></div><div class="toolbar-left"><span class="toolbar-count">${businesses.length} Lead</span>${button("إسناد", "crm-assign", "button ghost")}</div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Lead</th><th>Company</th><th>المصدر</th><th>Score</th><th>المرحلة</th><th>القيمة</th><th>المالك</th><th>آخر نشاط</th><th>الإجراء التالي</th></tr></thead><tbody>${businesses.map(b=>`<tr><td><button class="row-link mono" data-route="lead-profile" data-business="${b.id}">LEAD-${b.id.slice(4)}</button></td><td><button class="company-cell row-link" data-route="lead-profile" data-business="${b.id}"><i class="company-mark">${b.short.slice(0,1)}</i><span><b>${b.name}</b><small>${b.category}</small></span></button></td><td><span class="source"><i></i>${b.source}</span></td><td><span class="score ${b.score>=85?"high":""}">${b.score}</span></td><td><span class="status ${statusClass(b.stage)}">${stageArabic[b.stage]}</span></td><td>${sar(b.value)}</td><td>${b.owner}</td><td>${b.lastActivity}</td><td><button class="button ghost" data-action="create-task">Follow-up</button></td></tr>`).join("")}</tbody></table></div></section><section class="grid grid-3" style="margin-top:16px"><article class="card pad"><p class="eyebrow">Source clarity</p><h3 style="margin:0;font-size:15px">Google Maps مصدر، وليس المنتج</h3><p class="muted" style="font-size:10px;line-height:1.8">تظهر معه مصادر Website وImport وWhatsApp وReferral في CRM نفسه.</p></article><article class="card pad"><p class="eyebrow">Sales Copilot</p><h3 style="margin:0;font-size:15px">47 Lead لم تتم متابعتها</h3><p class="muted" style="font-size:10px;line-height:1.8">يمكن للذكاء إنشاء Follow-up أو ترتيب أولويات فريق المبيعات.</p></article><article class="card pad"><p class="eyebrow">Pipeline link</p><h3 style="margin:0;font-size:15px">${businesses.filter(b=>b.stage!=="New").length} Lead في مراحل نشطة</h3><p class="muted" style="font-size:10px;line-height:1.8">كل تغيير مرحلة يظهر في Pipeline والتحليلات.</p></article></section>`;
}

export function renderPipeline(ctx) {
  const { button, pageHead, sar } = ctx;
  const columnStages = ["New","Contacted","Qualified","Meeting","Proposal","Negotiation","Won"];
  return `${pageHead("Sales Pipeline", "رحلة الصفقات", "حرّك البطاقة بين المراحل. سيُحدّث الـPrototype المرحلة وقيمة Pipeline التجريبية فورًا.", `${button("عرض الصفقات", "route-deals", "button")}${button("إنشاء صفقة", "create-deal", "button primary")}`)}<section class="pipeline-board">${columnStages.map(stage=>{const cards=businesses.filter(b=>b.stage===stage);return `<article class="pipeline-column" data-drop-stage="${stage}"><header><div><b>${stageArabic[stage]}</b><small>${cards.length} صفقات</small></div><span>${sar(cards.reduce((n,b)=>n+b.value,0))}</span></header><div class="pipeline-cards">${cards.map(b=>`<article class="deal-card" draggable="true" data-drag-business="${b.id}"><div class="deal-card-head"><span class="score ${b.score>=85?"high":""}">${b.score}</span><button data-route="lead-profile" data-business="${b.id}">•••</button></div><button class="deal-company" data-route="lead-profile" data-business="${b.id}">${b.name}</button><p>${b.opportunity}</p><div class="deal-meta"><span>${sar(b.value)}</span><span>${b.owner}</span></div><div class="deal-next"><i></i>${b.lastActivity}</div></article>`).join("") || `<div class="pipeline-empty">اسحب صفقة هنا</div>`}</div></article>`;}).join("")}</section><section class="card pad" style="margin-top:16px"><div class="pipeline-note"><span class="pill success"><i></i>Drag & Drop</span><p>عند نقل العميل، تتغير مرحلة Lead نفسها. هذه هي العلاقة التي تجعل CRM وPipeline وDeal وجهات مختلفة لنفس السجل.</p></div></section>`;
}

export function renderInbox(ctx) {
  const { button, pageHead, sar } = ctx; const current = conversations.find(c=>c.id===state.selectedConversationId) || conversations[0]; const business = businesses.find(b=>b.id===current.businessId) || businesses[0];
  return `${pageHead("Unified Inbox", "المحادثة داخل سياق العميل", "الموظف لا يرى الرسائل وحدها؛ يرى الدرجة والفرصة ومرحلة البيع والأنشطة والملخص الذكي.", button("فتح Lead Profile", "route-lead-profile", "button"))}<section class="inbox-layout"><aside class="inbox-filters"><h3>المحادثات</h3>${[["الكل",conversations.length],["WhatsApp",1],["Instagram",1],["Web Chat",1],["بانتظار رد",2],["تحتاج تدخل بشري",1]].map(([x,n],i)=>`<button class="inbox-filter ${i===0?"active":""}">${x}<span>${n}</span></button>`).join("")}<div class="inbox-ai-note"><span>AI Coverage</span><b>72%</b><small>من المحادثات حُصلت على مساعدة أولية</small></div></aside><section class="conversation-list"><div class="conversation-search"><span>⌕</span><input placeholder="بحث في المحادثات"/></div>${conversations.map(c=>{const b=businesses.find(x=>x.id===c.businessId);return `<button class="conversation-item ${c.id===current.id?"active":""}" data-conversation-select="${c.id}"><i class="channel-icon">${c.channel.slice(0,1)}</i><div><b>${b?.short}</b><small>${c.preview}</small></div><span>${c.time}${c.unread?`<em>${c.unread}</em>`:""}</span></button>`}).join("")}</section><section class="conversation-pane"><header class="conversation-head"><div><b>${current.contact}</b><span><i></i>${current.channel} · ${business.name}</span></div><div>${button("AI Summary", "summarize-conversation", "button ghost")}${button("فتح العميل", "route-lead-profile", "button ghost")}</div></header><div class="messages">${current.messages.map(m=>`<div class="message ${m.from==="us"?"out":"in"}"><span>${m.text}</span><small>${m.from==="us"?"أنت · 10:40":"العميل · 10:42"}</small></div>`).join("")}</div><div class="suggested-replies"><span>Sales Copilot</span><button data-action="send-suggested">يسعدنا. يمكننا مراجعة رحلة الحجز الحالية خلال مكالمة قصيرة.</button><button data-action="send-suggested">هل يناسبكم اجتماع تقني هذا الأسبوع؟</button></div><div class="composer"><textarea placeholder="اكتب ردًا تجريبيًا..."></textarea>${button("إرسال", "send-mock-message", "button primary")}</div></section><aside class="context-panel"><p class="eyebrow">Customer Context</p><h3>${business.name}</h3><div class="context-score"><span class="score high">${business.score}</span><b>High Potential</b></div><div class="context-facts"><span><small>الفرصة</small><b>${business.opportunity}</b></span><span><small>Pipeline</small><b>${stageArabic[business.stage]}</b></span><span><small>القيمة</small><b>${sar(business.value)}</b></span><span><small>آخر نشاط</small><b>${business.lastActivity}</b></span></div><div class="ai-summary"><b>AI Summary</b><p>عميل مهتم بتحسين الحجز. أفضل إجراء هو تحويل الاهتمام إلى اجتماع تقني خلال 48 ساعة مع إبراز سرعة الاستجابة في WhatsApp.</p></div>${button("تأهيل العميل", "qualify-lead", "button primary")}</aside></section>`;
}

export function renderAgent(ctx) {
  const { button, pageHead, fmt, sar } = ctx; const on = state.agentActive !== false;
  const caps = ["تأهيل العميل","الإجابة عن الأسئلة","اقتراح الخدمات","جمع المعلومات","حجز اجتماع","إنشاء نشاط CRM","إنشاء مهمة","تحديث العميل","التصعيد للبشر"];
  return `${pageHead("AI Sales Agent", "Agent Control Center", "شاشة تحكم للوكيل الذكي: قواعد واضحة، تصعيد بشري، ومؤشرات على المساهمة في Pipeline — وليست نافذة Chatbot فقط.", button(on?"إيقاف Agent":"تفعيل Agent", "toggle-agent", `button ${on?"":"primary"}`))}<section class="agent-hero"><div><span class="pill ${on?"success":"danger"}"><i></i>${on?"Active":"Paused"}</span><h2>AI Agent ${on?"نشط ويعالج المحادثات المؤهلة":"موقوف مؤقتًا"}</h2><p>يقرأ السياق من العميل وCRM، يقترح الخطوة التالية، ويحوّل الحالات الحساسة إلى الموظف المناسب.</p></div><div class="agent-hero-metrics"><span><b>184</b>محادثة اليوم</span><span><b>37</b>Lead مؤهل</span><span><b>12</b>موعد محجوز</span><span><b>8</b>Human Handoffs</span><span><b>${sar(182000)}</b>Influenced Pipeline</span></div></section><section class="grid grid-2" style="margin-top:16px"><article class="card"><header class="card-head"><div><h2>قدرات Agent</h2><p>كل قدرة تؤدي إلى أثر قابل للظهور في CRM</p></div></header><div class="capability-grid">${caps.map((c,i)=>`<div><i>${String(i+1).padStart(2,"0")}</i><b>${c}</b><small>${i<4?"متاح في الردود الأولية":"يرتبط بسجل العميل"}</small></div>`).join("")}</div></article><article class="card"><header class="card-head"><div><h2>Agent Rules</h2><p>حدود واضحة قبل أي إجراء أو اقتراح</p></div>${button("إضافة قاعدة", "add-agent-rule", "button ghost")}</header><div class="rule-list">${[["الخصومات", "لا تقدم خصمًا أعلى من 10%"],["التسعير", "حوّل مفاوضات أعلى من SAR 50,000 إلى مدير المبيعات"],["العروض", "لا ترسل Proposal دون موافقة بشرية"],["المشاعر", "صعّد العميل الغاضب إلى موظف فورًا"]].map(([n,r])=>`<div><span>${n}</span><b>${r}</b><button data-action="edit-rule">تعديل</button></div>`).join("")}</div></article></section><section class="card" style="margin-top:16px"><header class="card-head"><div><h2>Agent Performance</h2><p>ملخص الحالات التي تحتاج تدخلًا أو مراجعة</p></div></header><div class="table-wrap"><table class="data-table"><thead><tr><th>العميل</th><th>القناة</th><th>ما فعله Agent</th><th>النتيجة</th><th>التدخل البشري</th></tr></thead><tbody>${businesses.slice(0,4).map((b,i)=>`<tr><td><button class="row-link" data-route="lead-profile" data-business="${b.id}">${b.name}</button></td><td>${i%2?"Instagram":"WhatsApp"}</td><td>${i%2?"جمع معلومات":"اقترح موعدًا"}</td><td><span class="status qualified">${i%2?"Qualified":"Meeting booked"}</span></td><td>${i===1?"مطلوب":"لا"}</td></tr>`).join("")}</tbody></table></div></section>`;
}

export function renderAutomation(ctx) {
  const { button, pageHead } = ctx;
  const nodes = [["Trigger","Lead Score > 80","trigger"],["Condition","Has WhatsApp","condition"],["Action","Add to High Priority","action"],["Action","Assign to Sales Team","action"],["Delay","30 minutes","delay"],["Action","Generate Personalized Message","action"],["Approval","Human Review","approval"],["Action","Send WhatsApp","action"],["Wait","Wait for Reply","delay"],["If Replied","Start AI Qualification","condition"],["If No Reply","Create Follow-up Task","condition"]];
  return `${pageHead("Automation", "Workflow Builder", "اربط الإشارة بالشرط والإجراء، مع تأخير وموافقة بشرية قبل التواصل. العقد التالية تجريبية وقابلة لإعادة الترتيب بصريًا.", `${button("قوالب", "show-templates", "button")}${button("حفظ Workflow", "save-workflow", "button primary")}`)}<section class="automation-layout"><aside class="automation-library"><h3>العُقد</h3>${[["Trigger","بدء من حدث"],["Condition","اختبر إشارة أو شرط"],["Action","نفذ إجراء في CRM أو Inbox"],["Delay","انتظر مدة محددة"],["Approval","اطلب موافقة بشرية"]].map(([a,b])=>`<button data-action="add-workflow-node"><b>${a}</b><small>${b}</small><i>+</i></button>`).join("")}<div class="automation-help"><b>منطق واضح</b><p>كل عقدة تشرح سبب انتقال العميل. في الإنتاج تصبح هذه إجراءات حقيقية بعد ربط الخدمات.</p></div></aside><article class="workflow-canvas"><header><div><span class="pill success"><i></i>Active</span><h2>High Opportunity → WhatsApp Qualification</h2><p>يقود العميل عالي الدرجة إلى رسالة مخصصة بعد مراجعة بشرية.</p></div><span class="mono">WF-028</span></header><div class="workflow-nodes">${nodes.map(([type,text,cls],i)=>`<div class="wf-node ${cls}"><small>${type}</small><b>${text}</b><i>${i<nodes.length-1?"↓":"✓"}</i></div>`).join("")}</div></article><aside class="workflow-side"><div class="card pad"><p class="eyebrow">الأثر المتوقع</p><h3 style="margin:0;font-size:18px">رفع سرعة أول متابعة</h3><p class="muted" style="font-size:10px;line-height:1.8">يبدأ Workflow فقط عندما تتوفر الإشارة والقناة والموافقة المطلوبة.</p><div class="workflow-stat"><span>دخلوا الـWorkflow هذا الأسبوع</span><b>46</b></div><div class="workflow-stat"><span>تم تأهيلهم</span><b>18</b></div></div><div class="card pad"><p class="eyebrow">الحماية</p><p class="muted" style="font-size:10px;line-height:1.8">لن يرسل الـPrototype رسائل حقيقية. زر الحفظ يغيّر حالة الواجهة فقط.</p></div></aside></section>`;
}
